// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dog_func (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V_ap_vld,
        line_buffer_delays_0_wp_V_read,
        line_buffer_delays_1_wp_V_read,
        line_buffer_delays_2_wp_V_read,
        line_buffer_delays_0_rp_V_read,
        line_buffer_delays_1_rp_V_read,
        line_buffer_delays_2_rp_V_read,
        line_buffer_delays_buffer_V_address0,
        line_buffer_delays_buffer_V_ce0,
        line_buffer_delays_buffer_V_q0,
        line_buffer_delays_buffer_V_address1,
        line_buffer_delays_buffer_V_ce1,
        line_buffer_delays_buffer_V_we1,
        line_buffer_delays_buffer_V_d1,
        line_buffer_delay_outs_V_address0,
        line_buffer_delay_outs_V_ce0,
        line_buffer_delay_outs_V_we0,
        line_buffer_delay_outs_V_d0,
        line_buffer_delay_outs_V_q0,
        line_buffer_delay_outs_V_address1,
        line_buffer_delay_outs_V_ce1,
        line_buffer_delay_outs_V_we1,
        line_buffer_delay_outs_V_d1,
        line_buffer_delay_outs_V_q1,
        in_V,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        in_V_blk_n
);

parameter    ap_ST_pp0_stg0_fsm_0 = 6'b1;
parameter    ap_ST_pp0_stg1_fsm_1 = 6'b10;
parameter    ap_ST_pp0_stg2_fsm_2 = 6'b100;
parameter    ap_ST_pp0_stg3_fsm_3 = 6'b1000;
parameter    ap_ST_pp0_stg4_fsm_4 = 6'b10000;
parameter    ap_ST_pp0_stg5_fsm_5 = 6'b100000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv3_2 = 3'b10;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv64_1 = 64'b1;
parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv64_2 = 64'b10;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_V_ap_vld;
input  [9:0] line_buffer_delays_0_wp_V_read;
input  [9:0] line_buffer_delays_1_wp_V_read;
input  [9:0] line_buffer_delays_2_wp_V_read;
input  [9:0] line_buffer_delays_0_rp_V_read;
input  [9:0] line_buffer_delays_1_rp_V_read;
input  [9:0] line_buffer_delays_2_rp_V_read;
output  [11:0] line_buffer_delays_buffer_V_address0;
output   line_buffer_delays_buffer_V_ce0;
input  [7:0] line_buffer_delays_buffer_V_q0;
output  [11:0] line_buffer_delays_buffer_V_address1;
output   line_buffer_delays_buffer_V_ce1;
output   line_buffer_delays_buffer_V_we1;
output  [7:0] line_buffer_delays_buffer_V_d1;
output  [1:0] line_buffer_delay_outs_V_address0;
output   line_buffer_delay_outs_V_ce0;
output   line_buffer_delay_outs_V_we0;
output  [7:0] line_buffer_delay_outs_V_d0;
input  [7:0] line_buffer_delay_outs_V_q0;
output  [1:0] line_buffer_delay_outs_V_address1;
output   line_buffer_delay_outs_V_ce1;
output   line_buffer_delay_outs_V_we1;
output  [7:0] line_buffer_delay_outs_V_d1;
input  [7:0] line_buffer_delay_outs_V_q1;
input  [7:0] in_V;
output  [9:0] ap_return_0;
output  [9:0] ap_return_1;
output  [9:0] ap_return_2;
output  [9:0] ap_return_3;
output  [9:0] ap_return_4;
output  [9:0] ap_return_5;
output  [23:0] ap_return_6;
output   in_V_blk_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[1:0] line_buffer_delay_outs_V_address0;
reg line_buffer_delay_outs_V_ce0;
reg line_buffer_delay_outs_V_we0;
reg[1:0] line_buffer_delay_outs_V_address1;
reg line_buffer_delay_outs_V_ce1;
reg line_buffer_delay_outs_V_we1;
reg in_V_blk_n;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_0;
reg    ap_sig_23;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_sig_cseq_ST_pp0_stg5_fsm_5;
reg    ap_sig_43;
reg   [7:0] reg_177;
reg    ap_sig_cseq_ST_pp0_stg2_fsm_2;
reg    ap_sig_96;
reg    ap_sig_cseq_ST_pp0_stg3_fsm_3;
reg    ap_sig_104;
wire   [1:0] line_buffer_delay_outs_V_addr_1_reg_229;
wire   [1:0] line_buffer_delay_outs_V_addr_reg_234;
reg    ap_sig_cseq_ST_pp0_stg1_fsm_1;
reg    ap_sig_120;
reg   [7:0] line_buffer_delay_outs_V_load_1_reg_240;
reg   [7:0] line_buffer_delay_outs_V_load_2_reg_252;
reg   [9:0] line_buffer_delays_2_wp_V_wri_reg_257;
reg   [9:0] line_buffer_delays_2_rp_V_wri_reg_262;
reg   [9:0] line_buffer_delays_1_wp_V_wri_reg_267;
reg    ap_sig_cseq_ST_pp0_stg4_fsm_4;
reg    ap_sig_137;
reg   [9:0] line_buffer_delays_1_rp_V_wri_reg_272;
reg    ap_reg_ppiten_pp0_iter0_preg;
reg   [9:0] ap_reg_ptbuf_line_buffer_delays_0_wp_V_read;
reg   [9:0] ap_reg_ptbuf_line_buffer_delays_1_wp_V_read;
reg   [9:0] ap_reg_ptbuf_line_buffer_delays_2_wp_V_read;
reg   [9:0] ap_reg_ptbuf_line_buffer_delays_0_rp_V_read;
reg   [9:0] ap_reg_ptbuf_line_buffer_delays_1_rp_V_read;
reg   [9:0] ap_reg_ptbuf_line_buffer_delays_2_rp_V_read;
reg   [7:0] ap_reg_ptbuf_in_V;
wire    grp_dog_func_1_fu_142_ap_start;
wire    grp_dog_func_1_fu_142_ap_done;
wire    grp_dog_func_1_fu_142_ap_idle;
wire    grp_dog_func_1_fu_142_ap_ready;
reg    grp_dog_func_1_fu_142_ap_ce;
reg   [9:0] grp_dog_func_1_fu_142_delay_wp_V_read;
reg   [9:0] grp_dog_func_1_fu_142_delay_rp_V_read;
wire   [11:0] grp_dog_func_1_fu_142_delay_buffer_V_address0;
wire    grp_dog_func_1_fu_142_delay_buffer_V_ce0;
wire   [11:0] grp_dog_func_1_fu_142_delay_buffer_V_address1;
wire    grp_dog_func_1_fu_142_delay_buffer_V_ce1;
wire    grp_dog_func_1_fu_142_delay_buffer_V_we1;
wire   [7:0] grp_dog_func_1_fu_142_delay_buffer_V_d1;
reg   [2:0] grp_dog_func_1_fu_142_tmp_5;
reg   [7:0] grp_dog_func_1_fu_142_in_V;
wire   [7:0] grp_dog_func_1_fu_142_ap_return_0;
wire   [9:0] grp_dog_func_1_fu_142_ap_return_1;
wire   [9:0] grp_dog_func_1_fu_142_ap_return_2;
wire    grp_dog_func_1_fu_142_in_V_blk_n;
reg    ap_reg_grp_dog_func_1_fu_142_ap_start;
wire   [23:0] out_data_V_write_assign_fu_183_p4;
reg   [5:0] ap_NS_fsm;
reg    ap_sig_pprstidle_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'b1;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_iter0_preg = 1'b0;
#0 ap_reg_grp_dog_func_1_fu_142_ap_start = 1'b0;
end

dog_func_1 grp_dog_func_1_fu_142(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dog_func_1_fu_142_ap_start),
    .ap_done(grp_dog_func_1_fu_142_ap_done),
    .ap_idle(grp_dog_func_1_fu_142_ap_idle),
    .ap_ready(grp_dog_func_1_fu_142_ap_ready),
    .in_V_ap_vld(1'b1),
    .ap_ce(grp_dog_func_1_fu_142_ap_ce),
    .delay_wp_V_read(grp_dog_func_1_fu_142_delay_wp_V_read),
    .delay_rp_V_read(grp_dog_func_1_fu_142_delay_rp_V_read),
    .delay_buffer_V_address0(grp_dog_func_1_fu_142_delay_buffer_V_address0),
    .delay_buffer_V_ce0(grp_dog_func_1_fu_142_delay_buffer_V_ce0),
    .delay_buffer_V_q0(line_buffer_delays_buffer_V_q0),
    .delay_buffer_V_address1(grp_dog_func_1_fu_142_delay_buffer_V_address1),
    .delay_buffer_V_ce1(grp_dog_func_1_fu_142_delay_buffer_V_ce1),
    .delay_buffer_V_we1(grp_dog_func_1_fu_142_delay_buffer_V_we1),
    .delay_buffer_V_d1(grp_dog_func_1_fu_142_delay_buffer_V_d1),
    .tmp_5(grp_dog_func_1_fu_142_tmp_5),
    .in_V(grp_dog_func_1_fu_142_in_V),
    .ap_return_0(grp_dog_func_1_fu_142_ap_return_0),
    .ap_return_1(grp_dog_func_1_fu_142_ap_return_1),
    .ap_return_2(grp_dog_func_1_fu_142_ap_return_2),
    .in_V_blk_n(grp_dog_func_1_fu_142_in_V_blk_n)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_pp0_stg0_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_dog_func_1_fu_142_ap_start <= 1'b0;
    end else begin
        if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0))))) begin
            ap_reg_grp_dog_func_1_fu_142_ap_start <= 1'b1;
        end else if ((1'b1 == grp_dog_func_1_fu_142_ap_ready)) begin
            ap_reg_grp_dog_func_1_fu_142_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0)) & ~(1'b1 == ap_reg_ppiten_pp0_it0))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_5) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & (in_V_ap_vld == 1'b0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_iter0_preg <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0)))) begin
            ap_reg_ppiten_pp0_iter0_preg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_reg_ppiten_pp0_it0)) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)) begin
            reg_177 <= line_buffer_delay_outs_V_q0;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) begin
            reg_177 <= line_buffer_delay_outs_V_q1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0)))) begin
        ap_reg_ptbuf_in_V <= in_V;
        ap_reg_ptbuf_line_buffer_delays_0_rp_V_read <= line_buffer_delays_0_rp_V_read;
        ap_reg_ptbuf_line_buffer_delays_0_wp_V_read <= line_buffer_delays_0_wp_V_read;
        ap_reg_ptbuf_line_buffer_delays_1_rp_V_read <= line_buffer_delays_1_rp_V_read;
        ap_reg_ptbuf_line_buffer_delays_1_wp_V_read <= line_buffer_delays_1_wp_V_read;
        ap_reg_ptbuf_line_buffer_delays_2_rp_V_read <= line_buffer_delays_2_rp_V_read;
        ap_reg_ptbuf_line_buffer_delays_2_wp_V_read <= line_buffer_delays_2_wp_V_read;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_1))) begin
        line_buffer_delay_outs_V_load_1_reg_240 <= line_buffer_delay_outs_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_2))) begin
        line_buffer_delay_outs_V_load_2_reg_252 <= line_buffer_delay_outs_V_q0;
        line_buffer_delays_2_rp_V_wri_reg_262 <= grp_dog_func_1_fu_142_ap_return_2;
        line_buffer_delays_2_wp_V_wri_reg_257 <= grp_dog_func_1_fu_142_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_4))) begin
        line_buffer_delays_1_rp_V_wri_reg_272 <= grp_dog_func_1_fu_142_ap_return_2;
        line_buffer_delays_1_wp_V_wri_reg_267 <= grp_dog_func_1_fu_142_ap_return_1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it0)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b0 == ap_reg_ppiten_pp0_it0) & (1'b0 == ap_reg_ppiten_pp0_it1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_5) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & (in_V_ap_vld == 1'b0)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0)) begin
        ap_reg_ppiten_pp0_it0 = ap_start;
    end else begin
        ap_reg_ppiten_pp0_it0 = ap_reg_ppiten_pp0_iter0_preg;
    end
end

always @ (*) begin
    if (ap_sig_23) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_120) begin
        ap_sig_cseq_ST_pp0_stg1_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg1_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_96) begin
        ap_sig_cseq_ST_pp0_stg2_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg2_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_104) begin
        ap_sig_cseq_ST_pp0_stg3_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg3_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_137) begin
        ap_sig_cseq_ST_pp0_stg4_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg4_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_43) begin
        ap_sig_cseq_ST_pp0_stg5_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg5_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b0 == ap_reg_ppiten_pp0_it0))) begin
        ap_sig_pprstidle_pp0 = 1'b1;
    end else begin
        ap_sig_pprstidle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_5) & (in_V_ap_vld == 1'b0)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0)))) begin
        grp_dog_func_1_fu_142_ap_ce = 1'b0;
    end else begin
        grp_dog_func_1_fu_142_ap_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_reg_ppiten_pp0_it0)) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_5)) begin
            grp_dog_func_1_fu_142_delay_rp_V_read = ap_reg_ptbuf_line_buffer_delays_0_rp_V_read;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)) begin
            grp_dog_func_1_fu_142_delay_rp_V_read = ap_reg_ptbuf_line_buffer_delays_1_rp_V_read;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) begin
            grp_dog_func_1_fu_142_delay_rp_V_read = ap_reg_ptbuf_line_buffer_delays_2_rp_V_read;
        end else begin
            grp_dog_func_1_fu_142_delay_rp_V_read = 'bx;
        end
    end else begin
        grp_dog_func_1_fu_142_delay_rp_V_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_reg_ppiten_pp0_it0)) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_5)) begin
            grp_dog_func_1_fu_142_delay_wp_V_read = ap_reg_ptbuf_line_buffer_delays_0_wp_V_read;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)) begin
            grp_dog_func_1_fu_142_delay_wp_V_read = ap_reg_ptbuf_line_buffer_delays_1_wp_V_read;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) begin
            grp_dog_func_1_fu_142_delay_wp_V_read = ap_reg_ptbuf_line_buffer_delays_2_wp_V_read;
        end else begin
            grp_dog_func_1_fu_142_delay_wp_V_read = 'bx;
        end
    end else begin
        grp_dog_func_1_fu_142_delay_wp_V_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_reg_ppiten_pp0_it0)) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_5)) begin
            grp_dog_func_1_fu_142_in_V = ap_reg_ptbuf_in_V;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)) begin
            grp_dog_func_1_fu_142_in_V = reg_177;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) begin
            grp_dog_func_1_fu_142_in_V = line_buffer_delay_outs_V_q0;
        end else begin
            grp_dog_func_1_fu_142_in_V = 'bx;
        end
    end else begin
        grp_dog_func_1_fu_142_in_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_reg_ppiten_pp0_it0)) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_5)) begin
            grp_dog_func_1_fu_142_tmp_5 = ap_const_lv3_0;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_3)) begin
            grp_dog_func_1_fu_142_tmp_5 = ap_const_lv3_1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) begin
            grp_dog_func_1_fu_142_tmp_5 = ap_const_lv3_2;
        end else begin
            grp_dog_func_1_fu_142_tmp_5 = 'bx;
        end
    end else begin
        grp_dog_func_1_fu_142_tmp_5 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_5))) begin
        in_V_blk_n = in_V_ap_vld;
    end else begin
        in_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_reg_ppiten_pp0_it0)) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) begin
            line_buffer_delay_outs_V_address0 = line_buffer_delay_outs_V_addr_1_reg_229;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) begin
            line_buffer_delay_outs_V_address0 = ap_const_lv64_0;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) begin
            line_buffer_delay_outs_V_address0 = ap_const_lv64_2;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0)) begin
            line_buffer_delay_outs_V_address0 = ap_const_lv64_1;
        end else begin
            line_buffer_delay_outs_V_address0 = 'bx;
        end
    end else begin
        line_buffer_delay_outs_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it1))) begin
        line_buffer_delay_outs_V_address1 = line_buffer_delay_outs_V_addr_reg_234;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_2))) begin
        line_buffer_delay_outs_V_address1 = ap_const_lv64_2;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_1))) begin
        line_buffer_delay_outs_V_address1 = ap_const_lv64_0;
    end else begin
        line_buffer_delay_outs_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_4)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0))))) begin
        line_buffer_delay_outs_V_ce0 = 1'b1;
    end else begin
        line_buffer_delay_outs_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_1)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0))))) begin
        line_buffer_delay_outs_V_ce1 = 1'b1;
    end else begin
        line_buffer_delay_outs_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_4))) begin
        line_buffer_delay_outs_V_we0 = 1'b1;
    end else begin
        line_buffer_delay_outs_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_2)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_0) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0))))) begin
        line_buffer_delay_outs_V_we1 = 1'b1;
    end else begin
        line_buffer_delay_outs_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_pp0_stg0_fsm_0 : begin
            if ((~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0)) & ~(1'b1 == ap_sig_pprstidle_pp0) & ~((1'b0 == ap_start) & (1'b0 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_1;
            end else if ((~((1'b1 == ap_reg_ppiten_pp0_it0) & (ap_start == 1'b0)) & (1'b1 == ap_sig_pprstidle_pp0))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
            end
        end
        ap_ST_pp0_stg1_fsm_1 : begin
            ap_NS_fsm = ap_ST_pp0_stg2_fsm_2;
        end
        ap_ST_pp0_stg2_fsm_2 : begin
            ap_NS_fsm = ap_ST_pp0_stg3_fsm_3;
        end
        ap_ST_pp0_stg3_fsm_3 : begin
            ap_NS_fsm = ap_ST_pp0_stg4_fsm_4;
        end
        ap_ST_pp0_stg4_fsm_4 : begin
            ap_NS_fsm = ap_ST_pp0_stg5_fsm_5;
        end
        ap_ST_pp0_stg5_fsm_5 : begin
            if (~((1'b1 == ap_reg_ppiten_pp0_it0) & (in_V_ap_vld == 1'b0))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg5_fsm_5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_return_0 = grp_dog_func_1_fu_142_ap_return_1;

assign ap_return_1 = line_buffer_delays_1_wp_V_wri_reg_267;

assign ap_return_2 = line_buffer_delays_2_wp_V_wri_reg_257;

assign ap_return_3 = grp_dog_func_1_fu_142_ap_return_2;

assign ap_return_4 = line_buffer_delays_1_rp_V_wri_reg_272;

assign ap_return_5 = line_buffer_delays_2_rp_V_wri_reg_262;

assign ap_return_6 = out_data_V_write_assign_fu_183_p4;

always @ (*) begin
    ap_sig_104 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_120 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_137 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_23 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_43 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_96 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

assign grp_dog_func_1_fu_142_ap_start = ap_reg_grp_dog_func_1_fu_142_ap_start;

assign line_buffer_delay_outs_V_addr_1_reg_229 = ap_const_lv64_1;

assign line_buffer_delay_outs_V_addr_reg_234 = ap_const_lv64_0;

assign line_buffer_delay_outs_V_d0 = grp_dog_func_1_fu_142_ap_return_0;

assign line_buffer_delay_outs_V_d1 = grp_dog_func_1_fu_142_ap_return_0;

assign line_buffer_delays_buffer_V_address0 = grp_dog_func_1_fu_142_delay_buffer_V_address0;

assign line_buffer_delays_buffer_V_address1 = grp_dog_func_1_fu_142_delay_buffer_V_address1;

assign line_buffer_delays_buffer_V_ce0 = grp_dog_func_1_fu_142_delay_buffer_V_ce0;

assign line_buffer_delays_buffer_V_ce1 = grp_dog_func_1_fu_142_delay_buffer_V_ce1;

assign line_buffer_delays_buffer_V_d1 = grp_dog_func_1_fu_142_delay_buffer_V_d1;

assign line_buffer_delays_buffer_V_we1 = grp_dog_func_1_fu_142_delay_buffer_V_we1;

assign out_data_V_write_assign_fu_183_p4 = {{{line_buffer_delay_outs_V_load_2_reg_252}, {line_buffer_delay_outs_V_load_1_reg_240}}, {reg_177}};

endmodule //dog_func
