-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.2
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dog_func is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_V_ap_vld : IN STD_LOGIC;
    line_buffer_delays_0_wp_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    line_buffer_delays_1_wp_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    line_buffer_delays_2_wp_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    line_buffer_delays_0_rp_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    line_buffer_delays_1_rp_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    line_buffer_delays_2_rp_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    line_buffer_delays_buffer_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    line_buffer_delays_buffer_V_ce0 : OUT STD_LOGIC;
    line_buffer_delays_buffer_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    line_buffer_delays_buffer_V_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    line_buffer_delays_buffer_V_ce1 : OUT STD_LOGIC;
    line_buffer_delays_buffer_V_we1 : OUT STD_LOGIC;
    line_buffer_delays_buffer_V_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    line_buffer_delay_outs_V_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    line_buffer_delay_outs_V_ce0 : OUT STD_LOGIC;
    line_buffer_delay_outs_V_we0 : OUT STD_LOGIC;
    line_buffer_delay_outs_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    line_buffer_delay_outs_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    line_buffer_delay_outs_V_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    line_buffer_delay_outs_V_ce1 : OUT STD_LOGIC;
    line_buffer_delay_outs_V_we1 : OUT STD_LOGIC;
    line_buffer_delay_outs_V_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    line_buffer_delay_outs_V_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_V : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (23 downto 0);
    in_V_blk_n : OUT STD_LOGIC );
end;


architecture behav of dog_func is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_pp0_stg0_fsm_0 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_pp0_stg1_fsm_1 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_pp0_stg2_fsm_2 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_pp0_stg3_fsm_3 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_pp0_stg4_fsm_4 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_pp0_stg5_fsm_5 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_pp0_stg0_fsm_0 : STD_LOGIC;
    signal ap_sig_23 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC;
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal ap_sig_cseq_ST_pp0_stg5_fsm_5 : STD_LOGIC;
    signal ap_sig_43 : BOOLEAN;
    signal reg_177 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_pp0_stg2_fsm_2 : STD_LOGIC;
    signal ap_sig_96 : BOOLEAN;
    signal ap_sig_cseq_ST_pp0_stg3_fsm_3 : STD_LOGIC;
    signal ap_sig_104 : BOOLEAN;
    signal line_buffer_delay_outs_V_addr_1_reg_229 : STD_LOGIC_VECTOR (1 downto 0);
    signal line_buffer_delay_outs_V_addr_reg_234 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_cseq_ST_pp0_stg1_fsm_1 : STD_LOGIC;
    signal ap_sig_120 : BOOLEAN;
    signal line_buffer_delay_outs_V_load_1_reg_240 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buffer_delay_outs_V_load_2_reg_252 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buffer_delays_2_wp_V_wri_reg_257 : STD_LOGIC_VECTOR (9 downto 0);
    signal line_buffer_delays_2_rp_V_wri_reg_262 : STD_LOGIC_VECTOR (9 downto 0);
    signal line_buffer_delays_1_wp_V_wri_reg_267 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_cseq_ST_pp0_stg4_fsm_4 : STD_LOGIC;
    signal ap_sig_137 : BOOLEAN;
    signal line_buffer_delays_1_rp_V_wri_reg_272 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ppiten_pp0_iter0_preg : STD_LOGIC := '0';
    signal ap_reg_ptbuf_line_buffer_delays_0_wp_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ptbuf_line_buffer_delays_1_wp_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ptbuf_line_buffer_delays_2_wp_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ptbuf_line_buffer_delays_0_rp_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ptbuf_line_buffer_delays_1_rp_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ptbuf_line_buffer_delays_2_rp_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ptbuf_in_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dog_func_1_fu_142_ap_start : STD_LOGIC;
    signal grp_dog_func_1_fu_142_ap_done : STD_LOGIC;
    signal grp_dog_func_1_fu_142_ap_idle : STD_LOGIC;
    signal grp_dog_func_1_fu_142_ap_ready : STD_LOGIC;
    signal grp_dog_func_1_fu_142_ap_ce : STD_LOGIC;
    signal grp_dog_func_1_fu_142_delay_wp_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dog_func_1_fu_142_delay_rp_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dog_func_1_fu_142_delay_buffer_V_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_dog_func_1_fu_142_delay_buffer_V_ce0 : STD_LOGIC;
    signal grp_dog_func_1_fu_142_delay_buffer_V_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_dog_func_1_fu_142_delay_buffer_V_ce1 : STD_LOGIC;
    signal grp_dog_func_1_fu_142_delay_buffer_V_we1 : STD_LOGIC;
    signal grp_dog_func_1_fu_142_delay_buffer_V_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dog_func_1_fu_142_tmp_5 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dog_func_1_fu_142_in_V : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dog_func_1_fu_142_ap_return_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dog_func_1_fu_142_ap_return_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dog_func_1_fu_142_ap_return_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_dog_func_1_fu_142_in_V_blk_n : STD_LOGIC;
    signal ap_reg_grp_dog_func_1_fu_142_ap_start : STD_LOGIC := '0';
    signal out_data_V_write_assign_fu_183_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_pprstidle_pp0 : STD_LOGIC;

    component dog_func_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_V_ap_vld : IN STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        delay_wp_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        delay_rp_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        delay_buffer_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        delay_buffer_V_ce0 : OUT STD_LOGIC;
        delay_buffer_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        delay_buffer_V_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
        delay_buffer_V_ce1 : OUT STD_LOGIC;
        delay_buffer_V_we1 : OUT STD_LOGIC;
        delay_buffer_V_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        tmp_5 : IN STD_LOGIC_VECTOR (2 downto 0);
        in_V : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        in_V_blk_n : OUT STD_LOGIC );
    end component;



begin
    grp_dog_func_1_fu_142 : component dog_func_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dog_func_1_fu_142_ap_start,
        ap_done => grp_dog_func_1_fu_142_ap_done,
        ap_idle => grp_dog_func_1_fu_142_ap_idle,
        ap_ready => grp_dog_func_1_fu_142_ap_ready,
        in_V_ap_vld => ap_const_logic_1,
        ap_ce => grp_dog_func_1_fu_142_ap_ce,
        delay_wp_V_read => grp_dog_func_1_fu_142_delay_wp_V_read,
        delay_rp_V_read => grp_dog_func_1_fu_142_delay_rp_V_read,
        delay_buffer_V_address0 => grp_dog_func_1_fu_142_delay_buffer_V_address0,
        delay_buffer_V_ce0 => grp_dog_func_1_fu_142_delay_buffer_V_ce0,
        delay_buffer_V_q0 => line_buffer_delays_buffer_V_q0,
        delay_buffer_V_address1 => grp_dog_func_1_fu_142_delay_buffer_V_address1,
        delay_buffer_V_ce1 => grp_dog_func_1_fu_142_delay_buffer_V_ce1,
        delay_buffer_V_we1 => grp_dog_func_1_fu_142_delay_buffer_V_we1,
        delay_buffer_V_d1 => grp_dog_func_1_fu_142_delay_buffer_V_d1,
        tmp_5 => grp_dog_func_1_fu_142_tmp_5,
        in_V => grp_dog_func_1_fu_142_in_V,
        ap_return_0 => grp_dog_func_1_fu_142_ap_return_0,
        ap_return_1 => grp_dog_func_1_fu_142_ap_return_1,
        ap_return_2 => grp_dog_func_1_fu_142_ap_return_2,
        in_V_blk_n => grp_dog_func_1_fu_142_in_V_blk_n);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_pp0_stg0_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_grp_dog_func_1_fu_142_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_dog_func_1_fu_142_ap_start <= ap_const_logic_0;
            else
                if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg2_fsm_2)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg4_fsm_4)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)))))) then 
                    ap_reg_grp_dog_func_1_fu_142_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_dog_func_1_fu_142_ap_ready)) then 
                    ap_reg_grp_dog_func_1_fu_142_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it0)))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg5_fsm_5) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (in_V_ap_vld = ap_const_logic_0))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_iter0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_iter0_preg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0))))) then 
                    ap_reg_ppiten_pp0_iter0_preg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    reg_177_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0)) then
                if ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg3_fsm_3)) then 
                    reg_177 <= line_buffer_delay_outs_V_q0;
                elsif ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg2_fsm_2)) then 
                    reg_177 <= line_buffer_delay_outs_V_q1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0))))) then
                ap_reg_ptbuf_in_V <= in_V;
                ap_reg_ptbuf_line_buffer_delays_0_rp_V_read <= line_buffer_delays_0_rp_V_read;
                ap_reg_ptbuf_line_buffer_delays_0_wp_V_read <= line_buffer_delays_0_wp_V_read;
                ap_reg_ptbuf_line_buffer_delays_1_rp_V_read <= line_buffer_delays_1_rp_V_read;
                ap_reg_ptbuf_line_buffer_delays_1_wp_V_read <= line_buffer_delays_1_wp_V_read;
                ap_reg_ptbuf_line_buffer_delays_2_rp_V_read <= line_buffer_delays_2_rp_V_read;
                ap_reg_ptbuf_line_buffer_delays_2_wp_V_read <= line_buffer_delays_2_wp_V_read;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_1))) then
                line_buffer_delay_outs_V_load_1_reg_240 <= line_buffer_delay_outs_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg2_fsm_2))) then
                line_buffer_delay_outs_V_load_2_reg_252 <= line_buffer_delay_outs_V_q0;
                line_buffer_delays_2_rp_V_wri_reg_262 <= grp_dog_func_1_fu_142_ap_return_2;
                line_buffer_delays_2_wp_V_wri_reg_257 <= grp_dog_func_1_fu_142_ap_return_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg4_fsm_4))) then
                line_buffer_delays_1_rp_V_wri_reg_272 <= grp_dog_func_1_fu_142_ap_return_2;
                line_buffer_delays_1_wp_V_wri_reg_267 <= grp_dog_func_1_fu_142_ap_return_1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it1, in_V_ap_vld, ap_sig_pprstidle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_pp0_stg0_fsm_0 => 
                if ((not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0))) and not((ap_const_logic_1 = ap_sig_pprstidle_pp0)) and not(((ap_const_logic_0 = ap_start) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it1))))) then
                    ap_NS_fsm <= ap_ST_pp0_stg1_fsm_1;
                elsif ((not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_sig_pprstidle_pp0))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_0;
                end if;
            when ap_ST_pp0_stg1_fsm_1 => 
                ap_NS_fsm <= ap_ST_pp0_stg2_fsm_2;
            when ap_ST_pp0_stg2_fsm_2 => 
                ap_NS_fsm <= ap_ST_pp0_stg3_fsm_3;
            when ap_ST_pp0_stg3_fsm_3 => 
                ap_NS_fsm <= ap_ST_pp0_stg4_fsm_4;
            when ap_ST_pp0_stg4_fsm_4 => 
                ap_NS_fsm <= ap_ST_pp0_stg5_fsm_5;
            when ap_ST_pp0_stg5_fsm_5 => 
                if (not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (in_V_ap_vld = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg5_fsm_5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;

    ap_done_assign_proc : process(ap_start, ap_sig_cseq_ST_pp0_stg0_fsm_0, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it1)
    begin
        if ((((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_pp0_stg0_fsm_0, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_0) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_reg_ppiten_pp0_it0, ap_sig_cseq_ST_pp0_stg5_fsm_5, in_V_ap_vld)
    begin
        if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg5_fsm_5) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (in_V_ap_vld = ap_const_logic_0))))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reg_ppiten_pp0_it0_assign_proc : process(ap_start, ap_sig_cseq_ST_pp0_stg0_fsm_0, ap_reg_ppiten_pp0_iter0_preg)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_0)) then 
            ap_reg_ppiten_pp0_it0 <= ap_start;
        else 
            ap_reg_ppiten_pp0_it0 <= ap_reg_ppiten_pp0_iter0_preg;
        end if; 
    end process;

    ap_return_0 <= grp_dog_func_1_fu_142_ap_return_1;
    ap_return_1 <= line_buffer_delays_1_wp_V_wri_reg_267;
    ap_return_2 <= line_buffer_delays_2_wp_V_wri_reg_257;
    ap_return_3 <= grp_dog_func_1_fu_142_ap_return_2;
    ap_return_4 <= line_buffer_delays_1_rp_V_wri_reg_272;
    ap_return_5 <= line_buffer_delays_2_rp_V_wri_reg_262;
    ap_return_6 <= out_data_V_write_assign_fu_183_p4;

    ap_sig_104_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_104 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    ap_sig_120_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_120 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    ap_sig_137_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_137 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    ap_sig_23_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_23 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    ap_sig_43_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_43 <= (ap_const_lv1_1 = ap_CS_fsm(5 downto 5));
    end process;


    ap_sig_96_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_96 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    ap_sig_cseq_ST_pp0_stg0_fsm_0_assign_proc : process(ap_sig_23)
    begin
        if (ap_sig_23) then 
            ap_sig_cseq_ST_pp0_stg0_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg0_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_pp0_stg1_fsm_1_assign_proc : process(ap_sig_120)
    begin
        if (ap_sig_120) then 
            ap_sig_cseq_ST_pp0_stg1_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg1_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_pp0_stg2_fsm_2_assign_proc : process(ap_sig_96)
    begin
        if (ap_sig_96) then 
            ap_sig_cseq_ST_pp0_stg2_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg2_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_pp0_stg3_fsm_3_assign_proc : process(ap_sig_104)
    begin
        if (ap_sig_104) then 
            ap_sig_cseq_ST_pp0_stg3_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg3_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_pp0_stg4_fsm_4_assign_proc : process(ap_sig_137)
    begin
        if (ap_sig_137) then 
            ap_sig_cseq_ST_pp0_stg4_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg4_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_pp0_stg5_fsm_5_assign_proc : process(ap_sig_43)
    begin
        if (ap_sig_43) then 
            ap_sig_cseq_ST_pp0_stg5_fsm_5 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg5_fsm_5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_pprstidle_pp0_assign_proc : process(ap_start, ap_reg_ppiten_pp0_it0)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it0))) then 
            ap_sig_pprstidle_pp0 <= ap_const_logic_1;
        else 
            ap_sig_pprstidle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    grp_dog_func_1_fu_142_ap_ce_assign_proc : process(ap_start, ap_sig_cseq_ST_pp0_stg0_fsm_0, ap_reg_ppiten_pp0_it0, ap_sig_cseq_ST_pp0_stg5_fsm_5, in_V_ap_vld)
    begin
        if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg5_fsm_5) and (in_V_ap_vld = ap_const_logic_0)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)))) then 
            grp_dog_func_1_fu_142_ap_ce <= ap_const_logic_0;
        else 
            grp_dog_func_1_fu_142_ap_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_dog_func_1_fu_142_ap_start <= ap_reg_grp_dog_func_1_fu_142_ap_start;

    grp_dog_func_1_fu_142_delay_rp_V_read_assign_proc : process(ap_reg_ppiten_pp0_it0, ap_sig_cseq_ST_pp0_stg5_fsm_5, ap_sig_cseq_ST_pp0_stg3_fsm_3, ap_sig_cseq_ST_pp0_stg1_fsm_1, ap_reg_ptbuf_line_buffer_delays_0_rp_V_read, ap_reg_ptbuf_line_buffer_delays_1_rp_V_read, ap_reg_ptbuf_line_buffer_delays_2_rp_V_read)
    begin
        if ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0)) then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg5_fsm_5)) then 
                grp_dog_func_1_fu_142_delay_rp_V_read <= ap_reg_ptbuf_line_buffer_delays_0_rp_V_read;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg3_fsm_3)) then 
                grp_dog_func_1_fu_142_delay_rp_V_read <= ap_reg_ptbuf_line_buffer_delays_1_rp_V_read;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_1)) then 
                grp_dog_func_1_fu_142_delay_rp_V_read <= ap_reg_ptbuf_line_buffer_delays_2_rp_V_read;
            else 
                grp_dog_func_1_fu_142_delay_rp_V_read <= "XXXXXXXXXX";
            end if;
        else 
            grp_dog_func_1_fu_142_delay_rp_V_read <= "XXXXXXXXXX";
        end if; 
    end process;


    grp_dog_func_1_fu_142_delay_wp_V_read_assign_proc : process(ap_reg_ppiten_pp0_it0, ap_sig_cseq_ST_pp0_stg5_fsm_5, ap_sig_cseq_ST_pp0_stg3_fsm_3, ap_sig_cseq_ST_pp0_stg1_fsm_1, ap_reg_ptbuf_line_buffer_delays_0_wp_V_read, ap_reg_ptbuf_line_buffer_delays_1_wp_V_read, ap_reg_ptbuf_line_buffer_delays_2_wp_V_read)
    begin
        if ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0)) then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg5_fsm_5)) then 
                grp_dog_func_1_fu_142_delay_wp_V_read <= ap_reg_ptbuf_line_buffer_delays_0_wp_V_read;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg3_fsm_3)) then 
                grp_dog_func_1_fu_142_delay_wp_V_read <= ap_reg_ptbuf_line_buffer_delays_1_wp_V_read;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_1)) then 
                grp_dog_func_1_fu_142_delay_wp_V_read <= ap_reg_ptbuf_line_buffer_delays_2_wp_V_read;
            else 
                grp_dog_func_1_fu_142_delay_wp_V_read <= "XXXXXXXXXX";
            end if;
        else 
            grp_dog_func_1_fu_142_delay_wp_V_read <= "XXXXXXXXXX";
        end if; 
    end process;


    grp_dog_func_1_fu_142_in_V_assign_proc : process(ap_reg_ppiten_pp0_it0, ap_sig_cseq_ST_pp0_stg5_fsm_5, line_buffer_delay_outs_V_q0, reg_177, ap_sig_cseq_ST_pp0_stg3_fsm_3, ap_sig_cseq_ST_pp0_stg1_fsm_1, ap_reg_ptbuf_in_V)
    begin
        if ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0)) then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg5_fsm_5)) then 
                grp_dog_func_1_fu_142_in_V <= ap_reg_ptbuf_in_V;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg3_fsm_3)) then 
                grp_dog_func_1_fu_142_in_V <= reg_177;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_1)) then 
                grp_dog_func_1_fu_142_in_V <= line_buffer_delay_outs_V_q0;
            else 
                grp_dog_func_1_fu_142_in_V <= "XXXXXXXX";
            end if;
        else 
            grp_dog_func_1_fu_142_in_V <= "XXXXXXXX";
        end if; 
    end process;


    grp_dog_func_1_fu_142_tmp_5_assign_proc : process(ap_reg_ppiten_pp0_it0, ap_sig_cseq_ST_pp0_stg5_fsm_5, ap_sig_cseq_ST_pp0_stg3_fsm_3, ap_sig_cseq_ST_pp0_stg1_fsm_1)
    begin
        if ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0)) then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg5_fsm_5)) then 
                grp_dog_func_1_fu_142_tmp_5 <= ap_const_lv3_0;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg3_fsm_3)) then 
                grp_dog_func_1_fu_142_tmp_5 <= ap_const_lv3_1;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_1)) then 
                grp_dog_func_1_fu_142_tmp_5 <= ap_const_lv3_2;
            else 
                grp_dog_func_1_fu_142_tmp_5 <= "XXX";
            end if;
        else 
            grp_dog_func_1_fu_142_tmp_5 <= "XXX";
        end if; 
    end process;


    in_V_blk_n_assign_proc : process(ap_reg_ppiten_pp0_it0, ap_sig_cseq_ST_pp0_stg5_fsm_5, in_V_ap_vld)
    begin
        if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg5_fsm_5))) then 
            in_V_blk_n <= in_V_ap_vld;
        else 
            in_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    line_buffer_delay_outs_V_addr_1_reg_229 <= ap_const_lv64_1(2 - 1 downto 0);
    line_buffer_delay_outs_V_addr_reg_234 <= ap_const_lv64_0(2 - 1 downto 0);

    line_buffer_delay_outs_V_address0_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_0, ap_reg_ppiten_pp0_it0, ap_sig_cseq_ST_pp0_stg2_fsm_2, line_buffer_delay_outs_V_addr_1_reg_229, ap_sig_cseq_ST_pp0_stg1_fsm_1, ap_sig_cseq_ST_pp0_stg4_fsm_4)
    begin
        if ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0)) then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg4_fsm_4)) then 
                line_buffer_delay_outs_V_address0 <= line_buffer_delay_outs_V_addr_1_reg_229;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg2_fsm_2)) then 
                line_buffer_delay_outs_V_address0 <= ap_const_lv64_0(2 - 1 downto 0);
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_1)) then 
                line_buffer_delay_outs_V_address0 <= ap_const_lv64_2(2 - 1 downto 0);
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_0)) then 
                line_buffer_delay_outs_V_address0 <= ap_const_lv64_1(2 - 1 downto 0);
            else 
                line_buffer_delay_outs_V_address0 <= "XX";
            end if;
        else 
            line_buffer_delay_outs_V_address0 <= "XX";
        end if; 
    end process;


    line_buffer_delay_outs_V_address1_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_0, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it1, ap_sig_cseq_ST_pp0_stg2_fsm_2, line_buffer_delay_outs_V_addr_reg_234, ap_sig_cseq_ST_pp0_stg1_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) then 
            line_buffer_delay_outs_V_address1 <= line_buffer_delay_outs_V_addr_reg_234;
        elsif (((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg2_fsm_2))) then 
            line_buffer_delay_outs_V_address1 <= ap_const_lv64_2(2 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_1))) then 
            line_buffer_delay_outs_V_address1 <= ap_const_lv64_0(2 - 1 downto 0);
        else 
            line_buffer_delay_outs_V_address1 <= "XX";
        end if; 
    end process;


    line_buffer_delay_outs_V_ce0_assign_proc : process(ap_start, ap_sig_cseq_ST_pp0_stg0_fsm_0, ap_reg_ppiten_pp0_it0, ap_sig_cseq_ST_pp0_stg2_fsm_2, ap_sig_cseq_ST_pp0_stg1_fsm_1, ap_sig_cseq_ST_pp0_stg4_fsm_4)
    begin
        if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg2_fsm_2)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_1)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg4_fsm_4)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)))))) then 
            line_buffer_delay_outs_V_ce0 <= ap_const_logic_1;
        else 
            line_buffer_delay_outs_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_delay_outs_V_ce1_assign_proc : process(ap_start, ap_sig_cseq_ST_pp0_stg0_fsm_0, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it1, ap_sig_cseq_ST_pp0_stg2_fsm_2, ap_sig_cseq_ST_pp0_stg1_fsm_1)
    begin
        if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg2_fsm_2)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_1)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)))))) then 
            line_buffer_delay_outs_V_ce1 <= ap_const_logic_1;
        else 
            line_buffer_delay_outs_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    line_buffer_delay_outs_V_d0 <= grp_dog_func_1_fu_142_ap_return_0;
    line_buffer_delay_outs_V_d1 <= grp_dog_func_1_fu_142_ap_return_0;

    line_buffer_delay_outs_V_we0_assign_proc : process(ap_reg_ppiten_pp0_it0, ap_sig_cseq_ST_pp0_stg4_fsm_4)
    begin
        if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg4_fsm_4)))) then 
            line_buffer_delay_outs_V_we0 <= ap_const_logic_1;
        else 
            line_buffer_delay_outs_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_delay_outs_V_we1_assign_proc : process(ap_start, ap_sig_cseq_ST_pp0_stg0_fsm_0, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it1, ap_sig_cseq_ST_pp0_stg2_fsm_2)
    begin
        if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg2_fsm_2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)))))) then 
            line_buffer_delay_outs_V_we1 <= ap_const_logic_1;
        else 
            line_buffer_delay_outs_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    line_buffer_delays_buffer_V_address0 <= grp_dog_func_1_fu_142_delay_buffer_V_address0;
    line_buffer_delays_buffer_V_address1 <= grp_dog_func_1_fu_142_delay_buffer_V_address1;
    line_buffer_delays_buffer_V_ce0 <= grp_dog_func_1_fu_142_delay_buffer_V_ce0;
    line_buffer_delays_buffer_V_ce1 <= grp_dog_func_1_fu_142_delay_buffer_V_ce1;
    line_buffer_delays_buffer_V_d1 <= grp_dog_func_1_fu_142_delay_buffer_V_d1;
    line_buffer_delays_buffer_V_we1 <= grp_dog_func_1_fu_142_delay_buffer_V_we1;
    out_data_V_write_assign_fu_183_p4 <= ((line_buffer_delay_outs_V_load_2_reg_252 & line_buffer_delay_outs_V_load_1_reg_240) & reg_177);
end behav;
