// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dog.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dog::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dog::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<12> dog::ap_ST_st1_fsm_0 = "1";
const sc_lv<12> dog::ap_ST_st2_fsm_1 = "10";
const sc_lv<12> dog::ap_ST_st3_fsm_2 = "100";
const sc_lv<12> dog::ap_ST_st4_fsm_3 = "1000";
const sc_lv<12> dog::ap_ST_st5_fsm_4 = "10000";
const sc_lv<12> dog::ap_ST_st6_fsm_5 = "100000";
const sc_lv<12> dog::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<12> dog::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<12> dog::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<12> dog::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<12> dog::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<12> dog::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<32> dog::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dog::ap_const_lv1_1 = "1";
const sc_lv<32> dog::ap_const_lv32_1 = "1";
const sc_lv<32> dog::ap_const_lv32_3 = "11";
const sc_lv<32> dog::ap_const_lv32_4 = "100";
const sc_lv<32> dog::ap_const_lv32_5 = "101";
const sc_lv<2> dog::ap_const_lv2_0 = "00";
const sc_lv<32> dog::ap_const_lv32_2 = "10";
const sc_lv<1> dog::ap_const_lv1_0 = "0";
const sc_lv<4> dog::ap_const_lv4_0 = "0000";
const sc_lv<32> dog::ap_const_lv32_B = "1011";
const sc_lv<32> dog::ap_const_lv32_6 = "110";
const sc_lv<32> dog::ap_const_lv32_7 = "111";
const sc_lv<32> dog::ap_const_lv32_8 = "1000";
const sc_lv<32> dog::ap_const_lv32_9 = "1001";
const sc_lv<32> dog::ap_const_lv32_A = "1010";
const sc_lv<10> dog::ap_const_lv10_0 = "0000000000";
const sc_lv<2> dog::ap_const_lv2_1 = "1";
const sc_lv<10> dog::ap_const_lv10_3F8 = "1111111000";
const sc_lv<2> dog::ap_const_lv2_2 = "10";
const sc_lv<4> dog::ap_const_lv4_9 = "1001";
const sc_lv<4> dog::ap_const_lv4_1 = "1";
const sc_lv<4> dog::ap_const_lv4_8 = "1000";

dog::dog(sc_module_name name) : sc_module(name), mVcdFile(0) {
    line_delays_buffer_V_U = new dog_line_delays_buffer_V("line_delays_buffer_V_U");
    line_delays_buffer_V_U->clk(ap_clk);
    line_delays_buffer_V_U->reset(ap_rst);
    line_delays_buffer_V_U->address0(grp_dog_func_fu_157_line_buffer_delays_buffer_V_address0);
    line_delays_buffer_V_U->ce0(grp_dog_func_fu_157_line_buffer_delays_buffer_V_ce0);
    line_delays_buffer_V_U->q0(line_delays_buffer_V_q0);
    line_delays_buffer_V_U->address1(grp_dog_func_fu_157_line_buffer_delays_buffer_V_address1);
    line_delays_buffer_V_U->ce1(grp_dog_func_fu_157_line_buffer_delays_buffer_V_ce1);
    line_delays_buffer_V_U->we1(grp_dog_func_fu_157_line_buffer_delays_buffer_V_we1);
    line_delays_buffer_V_U->d1(grp_dog_func_fu_157_line_buffer_delays_buffer_V_d1);
    line_delay_outs_V_U = new dog_line_delay_outs_V("line_delay_outs_V_U");
    line_delay_outs_V_U->clk(ap_clk);
    line_delay_outs_V_U->reset(ap_rst);
    line_delay_outs_V_U->address0(grp_dog_func_fu_157_line_buffer_delay_outs_V_address0);
    line_delay_outs_V_U->ce0(grp_dog_func_fu_157_line_buffer_delay_outs_V_ce0);
    line_delay_outs_V_U->we0(grp_dog_func_fu_157_line_buffer_delay_outs_V_we0);
    line_delay_outs_V_U->d0(grp_dog_func_fu_157_line_buffer_delay_outs_V_d0);
    line_delay_outs_V_U->q0(line_delay_outs_V_q0);
    line_delay_outs_V_U->address1(grp_dog_func_fu_157_line_buffer_delay_outs_V_address1);
    line_delay_outs_V_U->ce1(grp_dog_func_fu_157_line_buffer_delay_outs_V_ce1);
    line_delay_outs_V_U->we1(grp_dog_func_fu_157_line_buffer_delay_outs_V_we1);
    line_delay_outs_V_U->d1(grp_dog_func_fu_157_line_buffer_delay_outs_V_d1);
    line_delay_outs_V_U->q1(line_delay_outs_V_q1);
    grp_dog_func_fu_157 = new dog_func("grp_dog_func_fu_157");
    grp_dog_func_fu_157->ap_clk(ap_clk);
    grp_dog_func_fu_157->ap_rst(ap_rst);
    grp_dog_func_fu_157->ap_start(grp_dog_func_fu_157_ap_start);
    grp_dog_func_fu_157->ap_done(grp_dog_func_fu_157_ap_done);
    grp_dog_func_fu_157->ap_idle(grp_dog_func_fu_157_ap_idle);
    grp_dog_func_fu_157->ap_ready(grp_dog_func_fu_157_ap_ready);
    grp_dog_func_fu_157->in_V_ap_vld(ap_var_for_const0);
    grp_dog_func_fu_157->line_buffer_delays_0_wp_V_read(line_delays_0_wp_V_1_fu_86);
    grp_dog_func_fu_157->line_buffer_delays_1_wp_V_read(line_delays_1_wp_V_1_fu_90);
    grp_dog_func_fu_157->line_buffer_delays_2_wp_V_read(line_delays_2_wp_V_1_fu_94);
    grp_dog_func_fu_157->line_buffer_delays_0_rp_V_read(line_delays_0_rp_V_1_fu_98);
    grp_dog_func_fu_157->line_buffer_delays_1_rp_V_read(line_delays_1_rp_V_1_fu_102);
    grp_dog_func_fu_157->line_buffer_delays_2_rp_V_read(line_delays_2_rp_V_1_fu_106);
    grp_dog_func_fu_157->line_buffer_delays_buffer_V_address0(grp_dog_func_fu_157_line_buffer_delays_buffer_V_address0);
    grp_dog_func_fu_157->line_buffer_delays_buffer_V_ce0(grp_dog_func_fu_157_line_buffer_delays_buffer_V_ce0);
    grp_dog_func_fu_157->line_buffer_delays_buffer_V_q0(line_delays_buffer_V_q0);
    grp_dog_func_fu_157->line_buffer_delays_buffer_V_address1(grp_dog_func_fu_157_line_buffer_delays_buffer_V_address1);
    grp_dog_func_fu_157->line_buffer_delays_buffer_V_ce1(grp_dog_func_fu_157_line_buffer_delays_buffer_V_ce1);
    grp_dog_func_fu_157->line_buffer_delays_buffer_V_we1(grp_dog_func_fu_157_line_buffer_delays_buffer_V_we1);
    grp_dog_func_fu_157->line_buffer_delays_buffer_V_d1(grp_dog_func_fu_157_line_buffer_delays_buffer_V_d1);
    grp_dog_func_fu_157->line_buffer_delay_outs_V_address0(grp_dog_func_fu_157_line_buffer_delay_outs_V_address0);
    grp_dog_func_fu_157->line_buffer_delay_outs_V_ce0(grp_dog_func_fu_157_line_buffer_delay_outs_V_ce0);
    grp_dog_func_fu_157->line_buffer_delay_outs_V_we0(grp_dog_func_fu_157_line_buffer_delay_outs_V_we0);
    grp_dog_func_fu_157->line_buffer_delay_outs_V_d0(grp_dog_func_fu_157_line_buffer_delay_outs_V_d0);
    grp_dog_func_fu_157->line_buffer_delay_outs_V_q0(line_delay_outs_V_q0);
    grp_dog_func_fu_157->line_buffer_delay_outs_V_address1(grp_dog_func_fu_157_line_buffer_delay_outs_V_address1);
    grp_dog_func_fu_157->line_buffer_delay_outs_V_ce1(grp_dog_func_fu_157_line_buffer_delay_outs_V_ce1);
    grp_dog_func_fu_157->line_buffer_delay_outs_V_we1(grp_dog_func_fu_157_line_buffer_delay_outs_V_we1);
    grp_dog_func_fu_157->line_buffer_delay_outs_V_d1(grp_dog_func_fu_157_line_buffer_delay_outs_V_d1);
    grp_dog_func_fu_157->line_buffer_delay_outs_V_q1(line_delay_outs_V_q1);
    grp_dog_func_fu_157->in_V(in_V);
    grp_dog_func_fu_157->ap_return_0(grp_dog_func_fu_157_ap_return_0);
    grp_dog_func_fu_157->ap_return_1(grp_dog_func_fu_157_ap_return_1);
    grp_dog_func_fu_157->ap_return_2(grp_dog_func_fu_157_ap_return_2);
    grp_dog_func_fu_157->ap_return_3(grp_dog_func_fu_157_ap_return_3);
    grp_dog_func_fu_157->ap_return_4(grp_dog_func_fu_157_ap_return_4);
    grp_dog_func_fu_157->ap_return_5(grp_dog_func_fu_157_ap_return_5);
    grp_dog_func_fu_157->ap_return_6(grp_dog_func_fu_157_ap_return_6);
    grp_dog_func_fu_157->in_V_blk_n(grp_dog_func_fu_157_in_V_blk_n);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond1_fu_312_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond1_fu_312_p2 );

    SC_METHOD(thread_ap_sig_162);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_184);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_196);
    sensitive << ( ap_NS_fsm );

    SC_METHOD(thread_ap_sig_204);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_211);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_219);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_228);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_236);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_49);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_58);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_67);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_76);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_228 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_236 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_184 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_27 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_49 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_162 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_58 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_67 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_76 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_204 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_211 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_219 );

    SC_METHOD(thread_ap_sig_nseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_196 );

    SC_METHOD(thread_exitcond1_fu_312_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( p_s_reg_135 );

    SC_METHOD(thread_exitcond_fu_324_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( p_1_reg_146 );

    SC_METHOD(thread_grp_dog_func_fu_157_ap_start);
    sensitive << ( ap_reg_grp_dog_func_fu_157_ap_start );

    SC_METHOD(thread_i_V_fu_318_p2);
    sensitive << ( p_s_reg_135 );

    SC_METHOD(thread_j_V_fu_330_p2);
    sensitive << ( p_1_reg_146 );

    SC_METHOD(thread_line_delays_rp_V_0_1_fu_253_p3);
    sensitive << ( line_delays_rp_V_fu_54 );
    sensitive << ( sel_tmp2_fu_223_p2 );

    SC_METHOD(thread_line_delays_rp_V_1_1_fu_245_p3);
    sensitive << ( line_delays_rp_V_1_fu_58 );
    sensitive << ( sel_tmp2_fu_223_p2 );
    sensitive << ( sel_tmp5_fu_237_p3 );

    SC_METHOD(thread_line_delays_rp_V_2_1_fu_229_p3);
    sensitive << ( line_delays_rp_V_2_fu_62 );
    sensitive << ( sel_tmp2_fu_223_p2 );
    sensitive << ( sel_tmp1_fu_215_p3 );

    SC_METHOD(thread_line_delays_wp_V_1_fu_70);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_phi_fu_127_p4 );

    SC_METHOD(thread_line_delays_wp_V_2_fu_74);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_phi_fu_127_p4 );

    SC_METHOD(thread_line_delays_wp_V_fu_66);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_phi_fu_127_p4 );

    SC_METHOD(thread_out_data_V);
    sensitive << ( grp_dog_func_fu_157_ap_return_6 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_out_data_V_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_sel_tmp1_fu_215_p3);
    sensitive << ( line_delays_rp_V_2_fu_62 );
    sensitive << ( sel_tmp_fu_209_p2 );

    SC_METHOD(thread_sel_tmp2_fu_223_p2);
    sensitive << ( tmp_reg_123 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_sel_tmp5_fu_237_p3);
    sensitive << ( line_delays_rp_V_1_fu_58 );
    sensitive << ( sel_tmp_fu_209_p2 );

    SC_METHOD(thread_sel_tmp_fu_209_p2);
    sensitive << ( tmp_reg_123 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_tmp_1_fu_261_p2);
    sensitive << ( tmp_reg_123 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_tmp_9_fu_170_p2);
    sensitive << ( tmp_reg_123 );

    SC_METHOD(thread_tmp_phi_fu_127_p4);
    sensitive << ( tmp_reg_123 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_1_fu_261_p2 );
    sensitive << ( exitcond_fu_324_p2 );
    sensitive << ( exitcond1_fu_312_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000001";
    ap_reg_grp_dog_func_fu_157_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dog_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_V, "(port)in_V");
    sc_trace(mVcdFile, out_data_V, "(port)out_data_V");
    sc_trace(mVcdFile, out_data_V_ap_vld, "(port)out_data_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_27, "ap_sig_27");
    sc_trace(mVcdFile, tmp_9_fu_170_p2, "tmp_9_fu_170_p2");
    sc_trace(mVcdFile, tmp_9_reg_460, "tmp_9_reg_460");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_49, "ap_sig_49");
    sc_trace(mVcdFile, i_V_fu_318_p2, "i_V_fu_318_p2");
    sc_trace(mVcdFile, i_V_reg_513, "i_V_reg_513");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_58, "ap_sig_58");
    sc_trace(mVcdFile, j_V_fu_330_p2, "j_V_fu_330_p2");
    sc_trace(mVcdFile, j_V_reg_521, "j_V_reg_521");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_67, "ap_sig_67");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_76, "ap_sig_76");
    sc_trace(mVcdFile, line_delays_buffer_V_q0, "line_delays_buffer_V_q0");
    sc_trace(mVcdFile, line_delay_outs_V_q0, "line_delay_outs_V_q0");
    sc_trace(mVcdFile, line_delay_outs_V_q1, "line_delay_outs_V_q1");
    sc_trace(mVcdFile, grp_dog_func_fu_157_ap_start, "grp_dog_func_fu_157_ap_start");
    sc_trace(mVcdFile, grp_dog_func_fu_157_ap_done, "grp_dog_func_fu_157_ap_done");
    sc_trace(mVcdFile, grp_dog_func_fu_157_ap_idle, "grp_dog_func_fu_157_ap_idle");
    sc_trace(mVcdFile, grp_dog_func_fu_157_ap_ready, "grp_dog_func_fu_157_ap_ready");
    sc_trace(mVcdFile, grp_dog_func_fu_157_line_buffer_delays_buffer_V_address0, "grp_dog_func_fu_157_line_buffer_delays_buffer_V_address0");
    sc_trace(mVcdFile, grp_dog_func_fu_157_line_buffer_delays_buffer_V_ce0, "grp_dog_func_fu_157_line_buffer_delays_buffer_V_ce0");
    sc_trace(mVcdFile, grp_dog_func_fu_157_line_buffer_delays_buffer_V_address1, "grp_dog_func_fu_157_line_buffer_delays_buffer_V_address1");
    sc_trace(mVcdFile, grp_dog_func_fu_157_line_buffer_delays_buffer_V_ce1, "grp_dog_func_fu_157_line_buffer_delays_buffer_V_ce1");
    sc_trace(mVcdFile, grp_dog_func_fu_157_line_buffer_delays_buffer_V_we1, "grp_dog_func_fu_157_line_buffer_delays_buffer_V_we1");
    sc_trace(mVcdFile, grp_dog_func_fu_157_line_buffer_delays_buffer_V_d1, "grp_dog_func_fu_157_line_buffer_delays_buffer_V_d1");
    sc_trace(mVcdFile, grp_dog_func_fu_157_line_buffer_delay_outs_V_address0, "grp_dog_func_fu_157_line_buffer_delay_outs_V_address0");
    sc_trace(mVcdFile, grp_dog_func_fu_157_line_buffer_delay_outs_V_ce0, "grp_dog_func_fu_157_line_buffer_delay_outs_V_ce0");
    sc_trace(mVcdFile, grp_dog_func_fu_157_line_buffer_delay_outs_V_we0, "grp_dog_func_fu_157_line_buffer_delay_outs_V_we0");
    sc_trace(mVcdFile, grp_dog_func_fu_157_line_buffer_delay_outs_V_d0, "grp_dog_func_fu_157_line_buffer_delay_outs_V_d0");
    sc_trace(mVcdFile, grp_dog_func_fu_157_line_buffer_delay_outs_V_address1, "grp_dog_func_fu_157_line_buffer_delay_outs_V_address1");
    sc_trace(mVcdFile, grp_dog_func_fu_157_line_buffer_delay_outs_V_ce1, "grp_dog_func_fu_157_line_buffer_delay_outs_V_ce1");
    sc_trace(mVcdFile, grp_dog_func_fu_157_line_buffer_delay_outs_V_we1, "grp_dog_func_fu_157_line_buffer_delay_outs_V_we1");
    sc_trace(mVcdFile, grp_dog_func_fu_157_line_buffer_delay_outs_V_d1, "grp_dog_func_fu_157_line_buffer_delay_outs_V_d1");
    sc_trace(mVcdFile, grp_dog_func_fu_157_ap_return_0, "grp_dog_func_fu_157_ap_return_0");
    sc_trace(mVcdFile, grp_dog_func_fu_157_ap_return_1, "grp_dog_func_fu_157_ap_return_1");
    sc_trace(mVcdFile, grp_dog_func_fu_157_ap_return_2, "grp_dog_func_fu_157_ap_return_2");
    sc_trace(mVcdFile, grp_dog_func_fu_157_ap_return_3, "grp_dog_func_fu_157_ap_return_3");
    sc_trace(mVcdFile, grp_dog_func_fu_157_ap_return_4, "grp_dog_func_fu_157_ap_return_4");
    sc_trace(mVcdFile, grp_dog_func_fu_157_ap_return_5, "grp_dog_func_fu_157_ap_return_5");
    sc_trace(mVcdFile, grp_dog_func_fu_157_ap_return_6, "grp_dog_func_fu_157_ap_return_6");
    sc_trace(mVcdFile, grp_dog_func_fu_157_in_V_blk_n, "grp_dog_func_fu_157_in_V_blk_n");
    sc_trace(mVcdFile, tmp_phi_fu_127_p4, "tmp_phi_fu_127_p4");
    sc_trace(mVcdFile, tmp_reg_123, "tmp_reg_123");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_162, "ap_sig_162");
    sc_trace(mVcdFile, tmp_1_fu_261_p2, "tmp_1_fu_261_p2");
    sc_trace(mVcdFile, p_s_reg_135, "p_s_reg_135");
    sc_trace(mVcdFile, exitcond_fu_324_p2, "exitcond_fu_324_p2");
    sc_trace(mVcdFile, p_1_reg_146, "p_1_reg_146");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_184, "ap_sig_184");
    sc_trace(mVcdFile, exitcond1_fu_312_p2, "exitcond1_fu_312_p2");
    sc_trace(mVcdFile, ap_reg_grp_dog_func_fu_157_ap_start, "ap_reg_grp_dog_func_fu_157_ap_start");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_nseq_ST_st6_fsm_5, "ap_sig_nseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_196, "ap_sig_196");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_204, "ap_sig_204");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_211, "ap_sig_211");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_219, "ap_sig_219");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_228, "ap_sig_228");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_236, "ap_sig_236");
    sc_trace(mVcdFile, line_delays_rp_V_fu_54, "line_delays_rp_V_fu_54");
    sc_trace(mVcdFile, line_delays_rp_V_0_1_fu_253_p3, "line_delays_rp_V_0_1_fu_253_p3");
    sc_trace(mVcdFile, line_delays_rp_V_1_fu_58, "line_delays_rp_V_1_fu_58");
    sc_trace(mVcdFile, line_delays_rp_V_1_1_fu_245_p3, "line_delays_rp_V_1_1_fu_245_p3");
    sc_trace(mVcdFile, line_delays_rp_V_2_fu_62, "line_delays_rp_V_2_fu_62");
    sc_trace(mVcdFile, line_delays_rp_V_2_1_fu_229_p3, "line_delays_rp_V_2_1_fu_229_p3");
    sc_trace(mVcdFile, line_delays_wp_V_fu_66, "line_delays_wp_V_fu_66");
    sc_trace(mVcdFile, line_delays_wp_V_1_fu_70, "line_delays_wp_V_1_fu_70");
    sc_trace(mVcdFile, line_delays_wp_V_2_fu_74, "line_delays_wp_V_2_fu_74");
    sc_trace(mVcdFile, line_delays_0_wp_V_1_fu_86, "line_delays_0_wp_V_1_fu_86");
    sc_trace(mVcdFile, line_delays_1_wp_V_1_fu_90, "line_delays_1_wp_V_1_fu_90");
    sc_trace(mVcdFile, line_delays_2_wp_V_1_fu_94, "line_delays_2_wp_V_1_fu_94");
    sc_trace(mVcdFile, line_delays_0_rp_V_1_fu_98, "line_delays_0_rp_V_1_fu_98");
    sc_trace(mVcdFile, line_delays_1_rp_V_1_fu_102, "line_delays_1_rp_V_1_fu_102");
    sc_trace(mVcdFile, line_delays_2_rp_V_1_fu_106, "line_delays_2_rp_V_1_fu_106");
    sc_trace(mVcdFile, sel_tmp_fu_209_p2, "sel_tmp_fu_209_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_223_p2, "sel_tmp2_fu_223_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_215_p3, "sel_tmp1_fu_215_p3");
    sc_trace(mVcdFile, sel_tmp5_fu_237_p3, "sel_tmp5_fu_237_p3");
#endif

    }
    mHdltvinHandle.open("dog.hdltvin.dat");
    mHdltvoutHandle.open("dog.hdltvout.dat");
}

dog::~dog() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete line_delays_buffer_V_U;
    delete line_delay_outs_V_U;
    delete grp_dog_func_fu_157;
}

void dog::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dog::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_dog_func_fu_157_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_nseq_ST_st6_fsm_5.read()))) {
            ap_reg_grp_dog_func_fu_157_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_dog_func_fu_157_ap_ready.read())) {
            ap_reg_grp_dog_func_fu_157_ap_start = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        line_delays_0_rp_V_1_fu_98 = grp_dog_func_fu_157_ap_return_3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                !esl_seteq<1,1,1>(tmp_1_fu_261_p2.read(), ap_const_lv1_0))) {
        line_delays_0_rp_V_1_fu_98 = line_delays_rp_V_0_1_fu_253_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        line_delays_0_wp_V_1_fu_86 = grp_dog_func_fu_157_ap_return_0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                !esl_seteq<1,1,1>(tmp_1_fu_261_p2.read(), ap_const_lv1_0))) {
        line_delays_0_wp_V_1_fu_86 = line_delays_wp_V_fu_66.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        line_delays_1_rp_V_1_fu_102 = grp_dog_func_fu_157_ap_return_4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                !esl_seteq<1,1,1>(tmp_1_fu_261_p2.read(), ap_const_lv1_0))) {
        line_delays_1_rp_V_1_fu_102 = line_delays_rp_V_1_1_fu_245_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        line_delays_1_wp_V_1_fu_90 = grp_dog_func_fu_157_ap_return_1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                !esl_seteq<1,1,1>(tmp_1_fu_261_p2.read(), ap_const_lv1_0))) {
        line_delays_1_wp_V_1_fu_90 = line_delays_wp_V_1_fu_70.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        line_delays_2_rp_V_1_fu_106 = grp_dog_func_fu_157_ap_return_5.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                !esl_seteq<1,1,1>(tmp_1_fu_261_p2.read(), ap_const_lv1_0))) {
        line_delays_2_rp_V_1_fu_106 = line_delays_rp_V_2_1_fu_229_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        line_delays_2_wp_V_1_fu_94 = grp_dog_func_fu_157_ap_return_2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                !esl_seteq<1,1,1>(tmp_1_fu_261_p2.read(), ap_const_lv1_0))) {
        line_delays_2_wp_V_1_fu_94 = line_delays_wp_V_2_fu_74.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_312_p2.read()))) {
        p_1_reg_146 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        p_1_reg_146 = j_V_reg_521.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_324_p2.read()))) {
        p_s_reg_135 = i_V_reg_513.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                !esl_seteq<1,1,1>(tmp_1_fu_261_p2.read(), ap_const_lv1_0))) {
        p_s_reg_135 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         esl_seteq<1,1,1>(tmp_1_fu_261_p2.read(), ap_const_lv1_0))) {
        tmp_reg_123 = tmp_9_reg_460.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        tmp_reg_123 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        i_V_reg_513 = i_V_fu_318_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        j_V_reg_521 = j_V_fu_330_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        line_delays_rp_V_1_fu_58 = line_delays_rp_V_1_1_fu_245_p3.read();
        line_delays_rp_V_2_fu_62 = line_delays_rp_V_2_1_fu_229_p3.read();
        line_delays_rp_V_fu_54 = line_delays_rp_V_0_1_fu_253_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        tmp_9_reg_460 = tmp_9_fu_170_p2.read();
    }
}

void dog::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_312_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dog::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dog::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_312_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dog::thread_ap_sig_162() {
    ap_sig_162 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dog::thread_ap_sig_184() {
    ap_sig_184 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void dog::thread_ap_sig_196() {
    ap_sig_196 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_NS_fsm.read().range(5, 5));
}

void dog::thread_ap_sig_204() {
    ap_sig_204 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void dog::thread_ap_sig_211() {
    ap_sig_211 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void dog::thread_ap_sig_219() {
    ap_sig_219 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void dog::thread_ap_sig_228() {
    ap_sig_228 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void dog::thread_ap_sig_236() {
    ap_sig_236 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void dog::thread_ap_sig_27() {
    ap_sig_27 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dog::thread_ap_sig_49() {
    ap_sig_49 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dog::thread_ap_sig_58() {
    ap_sig_58 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void dog::thread_ap_sig_67() {
    ap_sig_67 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void dog::thread_ap_sig_76() {
    ap_sig_76 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void dog::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_228.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void dog::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_236.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void dog::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_184.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void dog::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_27.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dog::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_49.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void dog::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_162.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void dog::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_58.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void dog::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_67.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void dog::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_76.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void dog::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_204.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void dog::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_211.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void dog::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_219.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void dog::thread_ap_sig_nseq_ST_st6_fsm_5() {
    if (ap_sig_196.read()) {
        ap_sig_nseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_nseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void dog::thread_exitcond1_fu_312_p2() {
    exitcond1_fu_312_p2 = (!p_s_reg_135.read().is_01() || !ap_const_lv4_9.is_01())? sc_lv<1>(): sc_lv<1>(p_s_reg_135.read() == ap_const_lv4_9);
}

void dog::thread_exitcond_fu_324_p2() {
    exitcond_fu_324_p2 = (!p_1_reg_146.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(p_1_reg_146.read() == ap_const_lv4_8);
}

void dog::thread_grp_dog_func_fu_157_ap_start() {
    grp_dog_func_fu_157_ap_start = ap_reg_grp_dog_func_fu_157_ap_start.read();
}

void dog::thread_i_V_fu_318_p2() {
    i_V_fu_318_p2 = (!p_s_reg_135.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(p_s_reg_135.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dog::thread_j_V_fu_330_p2() {
    j_V_fu_330_p2 = (!p_1_reg_146.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(p_1_reg_146.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dog::thread_line_delays_rp_V_0_1_fu_253_p3() {
    line_delays_rp_V_0_1_fu_253_p3 = (!sel_tmp2_fu_223_p2.read()[0].is_01())? sc_lv<10>(): ((sel_tmp2_fu_223_p2.read()[0].to_bool())? ap_const_lv10_3F8: line_delays_rp_V_fu_54.read());
}

void dog::thread_line_delays_rp_V_1_1_fu_245_p3() {
    line_delays_rp_V_1_1_fu_245_p3 = (!sel_tmp2_fu_223_p2.read()[0].is_01())? sc_lv<10>(): ((sel_tmp2_fu_223_p2.read()[0].to_bool())? line_delays_rp_V_1_fu_58.read(): sel_tmp5_fu_237_p3.read());
}

void dog::thread_line_delays_rp_V_2_1_fu_229_p3() {
    line_delays_rp_V_2_1_fu_229_p3 = (!sel_tmp2_fu_223_p2.read()[0].is_01())? sc_lv<10>(): ((sel_tmp2_fu_223_p2.read()[0].to_bool())? line_delays_rp_V_2_fu_62.read(): sel_tmp1_fu_215_p3.read());
}

void dog::thread_line_delays_wp_V_1_fu_70() {
    line_delays_wp_V_1_fu_70 = ap_const_lv10_0;
}

void dog::thread_line_delays_wp_V_2_fu_74() {
    line_delays_wp_V_2_fu_74 = ap_const_lv10_0;
}

void dog::thread_line_delays_wp_V_fu_66() {
    line_delays_wp_V_fu_66 = ap_const_lv10_0;
}

void dog::thread_out_data_V() {
    out_data_V = grp_dog_func_fu_157_ap_return_6.read();
}

void dog::thread_out_data_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        out_data_V_ap_vld = ap_const_logic_1;
    } else {
        out_data_V_ap_vld = ap_const_logic_0;
    }
}

void dog::thread_sel_tmp1_fu_215_p3() {
    sel_tmp1_fu_215_p3 = (!sel_tmp_fu_209_p2.read()[0].is_01())? sc_lv<10>(): ((sel_tmp_fu_209_p2.read()[0].to_bool())? line_delays_rp_V_2_fu_62.read(): ap_const_lv10_3F8);
}

void dog::thread_sel_tmp2_fu_223_p2() {
    sel_tmp2_fu_223_p2 = (!tmp_reg_123.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_reg_123.read() == ap_const_lv2_0);
}

void dog::thread_sel_tmp5_fu_237_p3() {
    sel_tmp5_fu_237_p3 = (!sel_tmp_fu_209_p2.read()[0].is_01())? sc_lv<10>(): ((sel_tmp_fu_209_p2.read()[0].to_bool())? ap_const_lv10_3F8: line_delays_rp_V_1_fu_58.read());
}

void dog::thread_sel_tmp_fu_209_p2() {
    sel_tmp_fu_209_p2 = (!tmp_reg_123.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_reg_123.read() == ap_const_lv2_1);
}

void dog::thread_tmp_1_fu_261_p2() {
    tmp_1_fu_261_p2 = (!tmp_reg_123.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(tmp_reg_123.read() == ap_const_lv2_2);
}

void dog::thread_tmp_9_fu_170_p2() {
    tmp_9_fu_170_p2 = (!tmp_reg_123.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(tmp_reg_123.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void dog::thread_tmp_phi_fu_127_p4() {
    tmp_phi_fu_127_p4 = tmp_reg_123.read();
}

void dog::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(tmp_1_fu_261_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_312_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 16 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_324_p2.read())) {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXX";
            break;
    }
}

void dog::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_V\" :  \"" << in_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_data_V\" :  \"" << out_data_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_data_V_ap_vld\" :  \"" << out_data_V_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

