// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dog_HH_
#define _dog_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dog_func.h"
#include "dog_line_delays_buffer_V.h"
#include "dog_line_delay_outs_V.h"

namespace ap_rtl {

struct dog : public sc_module {
    // Port declarations 9
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > in_V;
    sc_out< sc_lv<24> > out_data_V;
    sc_out< sc_logic > out_data_V_ap_vld;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    dog(sc_module_name name);
    SC_HAS_PROCESS(dog);

    ~dog();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    dog_line_delays_buffer_V* line_delays_buffer_V_U;
    dog_line_delay_outs_V* line_delay_outs_V_U;
    dog_func* grp_dog_func_fu_157;
    sc_signal< sc_lv<12> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_27;
    sc_signal< sc_lv<2> > tmp_9_fu_170_p2;
    sc_signal< sc_lv<2> > tmp_9_reg_460;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_49;
    sc_signal< sc_lv<4> > i_V_fu_318_p2;
    sc_signal< sc_lv<4> > i_V_reg_513;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_58;
    sc_signal< sc_lv<4> > j_V_fu_330_p2;
    sc_signal< sc_lv<4> > j_V_reg_521;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_67;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_76;
    sc_signal< sc_lv<8> > line_delays_buffer_V_q0;
    sc_signal< sc_lv<8> > line_delay_outs_V_q0;
    sc_signal< sc_lv<8> > line_delay_outs_V_q1;
    sc_signal< sc_logic > grp_dog_func_fu_157_ap_start;
    sc_signal< sc_logic > grp_dog_func_fu_157_ap_done;
    sc_signal< sc_logic > grp_dog_func_fu_157_ap_idle;
    sc_signal< sc_logic > grp_dog_func_fu_157_ap_ready;
    sc_signal< sc_lv<12> > grp_dog_func_fu_157_line_buffer_delays_buffer_V_address0;
    sc_signal< sc_logic > grp_dog_func_fu_157_line_buffer_delays_buffer_V_ce0;
    sc_signal< sc_lv<12> > grp_dog_func_fu_157_line_buffer_delays_buffer_V_address1;
    sc_signal< sc_logic > grp_dog_func_fu_157_line_buffer_delays_buffer_V_ce1;
    sc_signal< sc_logic > grp_dog_func_fu_157_line_buffer_delays_buffer_V_we1;
    sc_signal< sc_lv<8> > grp_dog_func_fu_157_line_buffer_delays_buffer_V_d1;
    sc_signal< sc_lv<2> > grp_dog_func_fu_157_line_buffer_delay_outs_V_address0;
    sc_signal< sc_logic > grp_dog_func_fu_157_line_buffer_delay_outs_V_ce0;
    sc_signal< sc_logic > grp_dog_func_fu_157_line_buffer_delay_outs_V_we0;
    sc_signal< sc_lv<8> > grp_dog_func_fu_157_line_buffer_delay_outs_V_d0;
    sc_signal< sc_lv<2> > grp_dog_func_fu_157_line_buffer_delay_outs_V_address1;
    sc_signal< sc_logic > grp_dog_func_fu_157_line_buffer_delay_outs_V_ce1;
    sc_signal< sc_logic > grp_dog_func_fu_157_line_buffer_delay_outs_V_we1;
    sc_signal< sc_lv<8> > grp_dog_func_fu_157_line_buffer_delay_outs_V_d1;
    sc_signal< sc_lv<10> > grp_dog_func_fu_157_ap_return_0;
    sc_signal< sc_lv<10> > grp_dog_func_fu_157_ap_return_1;
    sc_signal< sc_lv<10> > grp_dog_func_fu_157_ap_return_2;
    sc_signal< sc_lv<10> > grp_dog_func_fu_157_ap_return_3;
    sc_signal< sc_lv<10> > grp_dog_func_fu_157_ap_return_4;
    sc_signal< sc_lv<10> > grp_dog_func_fu_157_ap_return_5;
    sc_signal< sc_lv<24> > grp_dog_func_fu_157_ap_return_6;
    sc_signal< sc_logic > grp_dog_func_fu_157_in_V_blk_n;
    sc_signal< sc_lv<2> > tmp_phi_fu_127_p4;
    sc_signal< sc_lv<2> > tmp_reg_123;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_162;
    sc_signal< sc_lv<1> > tmp_1_fu_261_p2;
    sc_signal< sc_lv<4> > p_s_reg_135;
    sc_signal< sc_lv<1> > exitcond_fu_324_p2;
    sc_signal< sc_lv<4> > p_1_reg_146;
    sc_signal< sc_logic > ap_sig_cseq_ST_st12_fsm_11;
    sc_signal< bool > ap_sig_184;
    sc_signal< sc_lv<1> > exitcond1_fu_312_p2;
    sc_signal< sc_logic > ap_reg_grp_dog_func_fu_157_ap_start;
    sc_signal< sc_lv<12> > ap_NS_fsm;
    sc_signal< sc_logic > ap_sig_nseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_196;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_204;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_7;
    sc_signal< bool > ap_sig_211;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_8;
    sc_signal< bool > ap_sig_219;
    sc_signal< sc_logic > ap_sig_cseq_ST_st10_fsm_9;
    sc_signal< bool > ap_sig_228;
    sc_signal< sc_logic > ap_sig_cseq_ST_st11_fsm_10;
    sc_signal< bool > ap_sig_236;
    sc_signal< sc_lv<10> > line_delays_rp_V_fu_54;
    sc_signal< sc_lv<10> > line_delays_rp_V_0_1_fu_253_p3;
    sc_signal< sc_lv<10> > line_delays_rp_V_1_fu_58;
    sc_signal< sc_lv<10> > line_delays_rp_V_1_1_fu_245_p3;
    sc_signal< sc_lv<10> > line_delays_rp_V_2_fu_62;
    sc_signal< sc_lv<10> > line_delays_rp_V_2_1_fu_229_p3;
    sc_signal< sc_lv<10> > line_delays_wp_V_fu_66;
    sc_signal< sc_lv<10> > line_delays_wp_V_1_fu_70;
    sc_signal< sc_lv<10> > line_delays_wp_V_2_fu_74;
    sc_signal< sc_lv<10> > line_delays_0_wp_V_1_fu_86;
    sc_signal< sc_lv<10> > line_delays_1_wp_V_1_fu_90;
    sc_signal< sc_lv<10> > line_delays_2_wp_V_1_fu_94;
    sc_signal< sc_lv<10> > line_delays_0_rp_V_1_fu_98;
    sc_signal< sc_lv<10> > line_delays_1_rp_V_1_fu_102;
    sc_signal< sc_lv<10> > line_delays_2_rp_V_1_fu_106;
    sc_signal< sc_lv<1> > sel_tmp_fu_209_p2;
    sc_signal< sc_lv<1> > sel_tmp2_fu_223_p2;
    sc_signal< sc_lv<10> > sel_tmp1_fu_215_p3;
    sc_signal< sc_lv<10> > sel_tmp5_fu_237_p3;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<12> ap_ST_st1_fsm_0;
    static const sc_lv<12> ap_ST_st2_fsm_1;
    static const sc_lv<12> ap_ST_st3_fsm_2;
    static const sc_lv<12> ap_ST_st4_fsm_3;
    static const sc_lv<12> ap_ST_st5_fsm_4;
    static const sc_lv<12> ap_ST_st6_fsm_5;
    static const sc_lv<12> ap_ST_st7_fsm_6;
    static const sc_lv<12> ap_ST_st8_fsm_7;
    static const sc_lv<12> ap_ST_st9_fsm_8;
    static const sc_lv<12> ap_ST_st10_fsm_9;
    static const sc_lv<12> ap_ST_st11_fsm_10;
    static const sc_lv<12> ap_ST_st12_fsm_11;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<10> ap_const_lv10_3F8;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<4> ap_const_lv4_9;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_8;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_162();
    void thread_ap_sig_184();
    void thread_ap_sig_196();
    void thread_ap_sig_204();
    void thread_ap_sig_211();
    void thread_ap_sig_219();
    void thread_ap_sig_228();
    void thread_ap_sig_236();
    void thread_ap_sig_27();
    void thread_ap_sig_49();
    void thread_ap_sig_58();
    void thread_ap_sig_67();
    void thread_ap_sig_76();
    void thread_ap_sig_cseq_ST_st10_fsm_9();
    void thread_ap_sig_cseq_ST_st11_fsm_10();
    void thread_ap_sig_cseq_ST_st12_fsm_11();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_ap_sig_cseq_ST_st8_fsm_7();
    void thread_ap_sig_cseq_ST_st9_fsm_8();
    void thread_ap_sig_nseq_ST_st6_fsm_5();
    void thread_exitcond1_fu_312_p2();
    void thread_exitcond_fu_324_p2();
    void thread_grp_dog_func_fu_157_ap_start();
    void thread_i_V_fu_318_p2();
    void thread_j_V_fu_330_p2();
    void thread_line_delays_rp_V_0_1_fu_253_p3();
    void thread_line_delays_rp_V_1_1_fu_245_p3();
    void thread_line_delays_rp_V_2_1_fu_229_p3();
    void thread_line_delays_wp_V_1_fu_70();
    void thread_line_delays_wp_V_2_fu_74();
    void thread_line_delays_wp_V_fu_66();
    void thread_out_data_V();
    void thread_out_data_V_ap_vld();
    void thread_sel_tmp1_fu_215_p3();
    void thread_sel_tmp2_fu_223_p2();
    void thread_sel_tmp5_fu_237_p3();
    void thread_sel_tmp_fu_209_p2();
    void thread_tmp_1_fu_261_p2();
    void thread_tmp_9_fu_170_p2();
    void thread_tmp_phi_fu_127_p4();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
