// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dog_func_HH_
#define _dog_func_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dog_func_1.h"

namespace ap_rtl {

struct dog_func : public sc_module {
    // Port declarations 39
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_logic > in_V_ap_vld;
    sc_in< sc_lv<10> > line_buffer_delays_0_wp_V_read;
    sc_in< sc_lv<10> > line_buffer_delays_1_wp_V_read;
    sc_in< sc_lv<10> > line_buffer_delays_2_wp_V_read;
    sc_in< sc_lv<10> > line_buffer_delays_0_rp_V_read;
    sc_in< sc_lv<10> > line_buffer_delays_1_rp_V_read;
    sc_in< sc_lv<10> > line_buffer_delays_2_rp_V_read;
    sc_out< sc_lv<12> > line_buffer_delays_buffer_V_address0;
    sc_out< sc_logic > line_buffer_delays_buffer_V_ce0;
    sc_in< sc_lv<8> > line_buffer_delays_buffer_V_q0;
    sc_out< sc_lv<12> > line_buffer_delays_buffer_V_address1;
    sc_out< sc_logic > line_buffer_delays_buffer_V_ce1;
    sc_out< sc_logic > line_buffer_delays_buffer_V_we1;
    sc_out< sc_lv<8> > line_buffer_delays_buffer_V_d1;
    sc_out< sc_lv<2> > line_buffer_delay_outs_V_address0;
    sc_out< sc_logic > line_buffer_delay_outs_V_ce0;
    sc_out< sc_logic > line_buffer_delay_outs_V_we0;
    sc_out< sc_lv<8> > line_buffer_delay_outs_V_d0;
    sc_in< sc_lv<8> > line_buffer_delay_outs_V_q0;
    sc_out< sc_lv<2> > line_buffer_delay_outs_V_address1;
    sc_out< sc_logic > line_buffer_delay_outs_V_ce1;
    sc_out< sc_logic > line_buffer_delay_outs_V_we1;
    sc_out< sc_lv<8> > line_buffer_delay_outs_V_d1;
    sc_in< sc_lv<8> > line_buffer_delay_outs_V_q1;
    sc_in< sc_lv<8> > in_V;
    sc_out< sc_lv<10> > ap_return_0;
    sc_out< sc_lv<10> > ap_return_1;
    sc_out< sc_lv<10> > ap_return_2;
    sc_out< sc_lv<10> > ap_return_3;
    sc_out< sc_lv<10> > ap_return_4;
    sc_out< sc_lv<10> > ap_return_5;
    sc_out< sc_lv<24> > ap_return_6;
    sc_out< sc_logic > in_V_blk_n;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    dog_func(sc_module_name name);
    SC_HAS_PROCESS(dog_func);

    ~dog_func();

    sc_trace_file* mVcdFile;

    dog_func_1* grp_dog_func_1_fu_142;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_0;
    sc_signal< bool > ap_sig_23;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg5_fsm_5;
    sc_signal< bool > ap_sig_43;
    sc_signal< sc_lv<8> > reg_177;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg2_fsm_2;
    sc_signal< bool > ap_sig_96;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg3_fsm_3;
    sc_signal< bool > ap_sig_104;
    sc_signal< sc_lv<2> > line_buffer_delay_outs_V_addr_1_reg_229;
    sc_signal< sc_lv<2> > line_buffer_delay_outs_V_addr_reg_234;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg1_fsm_1;
    sc_signal< bool > ap_sig_120;
    sc_signal< sc_lv<8> > line_buffer_delay_outs_V_load_1_reg_240;
    sc_signal< sc_lv<8> > line_buffer_delay_outs_V_load_2_reg_252;
    sc_signal< sc_lv<10> > line_buffer_delays_2_wp_V_wri_reg_257;
    sc_signal< sc_lv<10> > line_buffer_delays_2_rp_V_wri_reg_262;
    sc_signal< sc_lv<10> > line_buffer_delays_1_wp_V_wri_reg_267;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg4_fsm_4;
    sc_signal< bool > ap_sig_137;
    sc_signal< sc_lv<10> > line_buffer_delays_1_rp_V_wri_reg_272;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_iter0_preg;
    sc_signal< sc_lv<10> > ap_reg_ptbuf_line_buffer_delays_0_wp_V_read;
    sc_signal< sc_lv<10> > ap_reg_ptbuf_line_buffer_delays_1_wp_V_read;
    sc_signal< sc_lv<10> > ap_reg_ptbuf_line_buffer_delays_2_wp_V_read;
    sc_signal< sc_lv<10> > ap_reg_ptbuf_line_buffer_delays_0_rp_V_read;
    sc_signal< sc_lv<10> > ap_reg_ptbuf_line_buffer_delays_1_rp_V_read;
    sc_signal< sc_lv<10> > ap_reg_ptbuf_line_buffer_delays_2_rp_V_read;
    sc_signal< sc_lv<8> > ap_reg_ptbuf_in_V;
    sc_signal< sc_logic > grp_dog_func_1_fu_142_ap_start;
    sc_signal< sc_logic > grp_dog_func_1_fu_142_ap_done;
    sc_signal< sc_logic > grp_dog_func_1_fu_142_ap_idle;
    sc_signal< sc_logic > grp_dog_func_1_fu_142_ap_ready;
    sc_signal< sc_logic > grp_dog_func_1_fu_142_ap_ce;
    sc_signal< sc_lv<10> > grp_dog_func_1_fu_142_delay_wp_V_read;
    sc_signal< sc_lv<10> > grp_dog_func_1_fu_142_delay_rp_V_read;
    sc_signal< sc_lv<12> > grp_dog_func_1_fu_142_delay_buffer_V_address0;
    sc_signal< sc_logic > grp_dog_func_1_fu_142_delay_buffer_V_ce0;
    sc_signal< sc_lv<12> > grp_dog_func_1_fu_142_delay_buffer_V_address1;
    sc_signal< sc_logic > grp_dog_func_1_fu_142_delay_buffer_V_ce1;
    sc_signal< sc_logic > grp_dog_func_1_fu_142_delay_buffer_V_we1;
    sc_signal< sc_lv<8> > grp_dog_func_1_fu_142_delay_buffer_V_d1;
    sc_signal< sc_lv<3> > grp_dog_func_1_fu_142_tmp_5;
    sc_signal< sc_lv<8> > grp_dog_func_1_fu_142_in_V;
    sc_signal< sc_lv<8> > grp_dog_func_1_fu_142_ap_return_0;
    sc_signal< sc_lv<10> > grp_dog_func_1_fu_142_ap_return_1;
    sc_signal< sc_lv<10> > grp_dog_func_1_fu_142_ap_return_2;
    sc_signal< sc_logic > grp_dog_func_1_fu_142_in_V_blk_n;
    sc_signal< sc_logic > ap_reg_grp_dog_func_1_fu_142_ap_start;
    sc_signal< sc_lv<24> > out_data_V_write_assign_fu_183_p4;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    sc_signal< sc_logic > ap_sig_pprstidle_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_pp0_stg0_fsm_0;
    static const sc_lv<6> ap_ST_pp0_stg1_fsm_1;
    static const sc_lv<6> ap_ST_pp0_stg2_fsm_2;
    static const sc_lv<6> ap_ST_pp0_stg3_fsm_3;
    static const sc_lv<6> ap_ST_pp0_stg4_fsm_4;
    static const sc_lv<6> ap_ST_pp0_stg5_fsm_5;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<3> ap_const_lv3_2;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_2;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_reg_ppiten_pp0_it0();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_2();
    void thread_ap_return_3();
    void thread_ap_return_4();
    void thread_ap_return_5();
    void thread_ap_return_6();
    void thread_ap_sig_104();
    void thread_ap_sig_120();
    void thread_ap_sig_137();
    void thread_ap_sig_23();
    void thread_ap_sig_43();
    void thread_ap_sig_96();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_0();
    void thread_ap_sig_cseq_ST_pp0_stg1_fsm_1();
    void thread_ap_sig_cseq_ST_pp0_stg2_fsm_2();
    void thread_ap_sig_cseq_ST_pp0_stg3_fsm_3();
    void thread_ap_sig_cseq_ST_pp0_stg4_fsm_4();
    void thread_ap_sig_cseq_ST_pp0_stg5_fsm_5();
    void thread_ap_sig_pprstidle_pp0();
    void thread_grp_dog_func_1_fu_142_ap_ce();
    void thread_grp_dog_func_1_fu_142_ap_start();
    void thread_grp_dog_func_1_fu_142_delay_rp_V_read();
    void thread_grp_dog_func_1_fu_142_delay_wp_V_read();
    void thread_grp_dog_func_1_fu_142_in_V();
    void thread_grp_dog_func_1_fu_142_tmp_5();
    void thread_in_V_blk_n();
    void thread_line_buffer_delay_outs_V_addr_1_reg_229();
    void thread_line_buffer_delay_outs_V_addr_reg_234();
    void thread_line_buffer_delay_outs_V_address0();
    void thread_line_buffer_delay_outs_V_address1();
    void thread_line_buffer_delay_outs_V_ce0();
    void thread_line_buffer_delay_outs_V_ce1();
    void thread_line_buffer_delay_outs_V_d0();
    void thread_line_buffer_delay_outs_V_d1();
    void thread_line_buffer_delay_outs_V_we0();
    void thread_line_buffer_delay_outs_V_we1();
    void thread_line_buffer_delays_buffer_V_address0();
    void thread_line_buffer_delays_buffer_V_address1();
    void thread_line_buffer_delays_buffer_V_ce0();
    void thread_line_buffer_delays_buffer_V_ce1();
    void thread_line_buffer_delays_buffer_V_d1();
    void thread_line_buffer_delays_buffer_V_we1();
    void thread_out_data_V_write_assign_fu_183_p4();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
