// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dog_func.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dog_func::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dog_func::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> dog_func::ap_ST_pp0_stg0_fsm_0 = "1";
const sc_lv<6> dog_func::ap_ST_pp0_stg1_fsm_1 = "10";
const sc_lv<6> dog_func::ap_ST_pp0_stg2_fsm_2 = "100";
const sc_lv<6> dog_func::ap_ST_pp0_stg3_fsm_3 = "1000";
const sc_lv<6> dog_func::ap_ST_pp0_stg4_fsm_4 = "10000";
const sc_lv<6> dog_func::ap_ST_pp0_stg5_fsm_5 = "100000";
const sc_lv<32> dog_func::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dog_func::ap_const_lv1_1 = "1";
const sc_lv<32> dog_func::ap_const_lv32_5 = "101";
const sc_lv<32> dog_func::ap_const_lv32_2 = "10";
const sc_lv<32> dog_func::ap_const_lv32_3 = "11";
const sc_lv<32> dog_func::ap_const_lv32_1 = "1";
const sc_lv<32> dog_func::ap_const_lv32_4 = "100";
const sc_lv<3> dog_func::ap_const_lv3_2 = "10";
const sc_lv<3> dog_func::ap_const_lv3_1 = "1";
const sc_lv<3> dog_func::ap_const_lv3_0 = "000";
const sc_lv<64> dog_func::ap_const_lv64_1 = "1";
const sc_lv<64> dog_func::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> dog_func::ap_const_lv64_2 = "10";

dog_func::dog_func(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_dog_func_1_fu_142 = new dog_func_1("grp_dog_func_1_fu_142");
    grp_dog_func_1_fu_142->ap_clk(ap_clk);
    grp_dog_func_1_fu_142->ap_rst(ap_rst);
    grp_dog_func_1_fu_142->ap_start(grp_dog_func_1_fu_142_ap_start);
    grp_dog_func_1_fu_142->ap_done(grp_dog_func_1_fu_142_ap_done);
    grp_dog_func_1_fu_142->ap_idle(grp_dog_func_1_fu_142_ap_idle);
    grp_dog_func_1_fu_142->ap_ready(grp_dog_func_1_fu_142_ap_ready);
    grp_dog_func_1_fu_142->in_V_ap_vld(ap_var_for_const0);
    grp_dog_func_1_fu_142->ap_ce(grp_dog_func_1_fu_142_ap_ce);
    grp_dog_func_1_fu_142->delay_wp_V_read(grp_dog_func_1_fu_142_delay_wp_V_read);
    grp_dog_func_1_fu_142->delay_rp_V_read(grp_dog_func_1_fu_142_delay_rp_V_read);
    grp_dog_func_1_fu_142->delay_buffer_V_address0(grp_dog_func_1_fu_142_delay_buffer_V_address0);
    grp_dog_func_1_fu_142->delay_buffer_V_ce0(grp_dog_func_1_fu_142_delay_buffer_V_ce0);
    grp_dog_func_1_fu_142->delay_buffer_V_q0(line_buffer_delays_buffer_V_q0);
    grp_dog_func_1_fu_142->delay_buffer_V_address1(grp_dog_func_1_fu_142_delay_buffer_V_address1);
    grp_dog_func_1_fu_142->delay_buffer_V_ce1(grp_dog_func_1_fu_142_delay_buffer_V_ce1);
    grp_dog_func_1_fu_142->delay_buffer_V_we1(grp_dog_func_1_fu_142_delay_buffer_V_we1);
    grp_dog_func_1_fu_142->delay_buffer_V_d1(grp_dog_func_1_fu_142_delay_buffer_V_d1);
    grp_dog_func_1_fu_142->tmp_5(grp_dog_func_1_fu_142_tmp_5);
    grp_dog_func_1_fu_142->in_V(grp_dog_func_1_fu_142_in_V);
    grp_dog_func_1_fu_142->ap_return_0(grp_dog_func_1_fu_142_ap_return_0);
    grp_dog_func_1_fu_142->ap_return_1(grp_dog_func_1_fu_142_ap_return_1);
    grp_dog_func_1_fu_142->ap_return_2(grp_dog_func_1_fu_142_ap_return_2);
    grp_dog_func_1_fu_142->in_V_blk_n(grp_dog_func_1_fu_142_in_V_blk_n);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_5 );
    sensitive << ( in_V_ap_vld );

    SC_METHOD(thread_ap_reg_ppiten_pp0_it0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_iter0_preg );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( grp_dog_func_1_fu_142_ap_return_1 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( line_buffer_delays_1_wp_V_wri_reg_267 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( line_buffer_delays_2_wp_V_wri_reg_257 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( grp_dog_func_1_fu_142_ap_return_2 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( line_buffer_delays_1_rp_V_wri_reg_272 );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( line_buffer_delays_2_rp_V_wri_reg_262 );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( out_data_V_write_assign_fu_183_p4 );

    SC_METHOD(thread_ap_sig_104);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_120);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_137);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_43);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_96);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_0);
    sensitive << ( ap_sig_23 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg1_fsm_1);
    sensitive << ( ap_sig_120 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg2_fsm_2);
    sensitive << ( ap_sig_96 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg3_fsm_3);
    sensitive << ( ap_sig_104 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg4_fsm_4);
    sensitive << ( ap_sig_137 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg5_fsm_5);
    sensitive << ( ap_sig_43 );

    SC_METHOD(thread_ap_sig_pprstidle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_grp_dog_func_1_fu_142_ap_ce);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_5 );
    sensitive << ( in_V_ap_vld );

    SC_METHOD(thread_grp_dog_func_1_fu_142_ap_start);
    sensitive << ( ap_reg_grp_dog_func_1_fu_142_ap_start );

    SC_METHOD(thread_grp_dog_func_1_fu_142_delay_rp_V_read);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_reg_ptbuf_line_buffer_delays_0_rp_V_read );
    sensitive << ( ap_reg_ptbuf_line_buffer_delays_1_rp_V_read );
    sensitive << ( ap_reg_ptbuf_line_buffer_delays_2_rp_V_read );

    SC_METHOD(thread_grp_dog_func_1_fu_142_delay_wp_V_read);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_reg_ptbuf_line_buffer_delays_0_wp_V_read );
    sensitive << ( ap_reg_ptbuf_line_buffer_delays_1_wp_V_read );
    sensitive << ( ap_reg_ptbuf_line_buffer_delays_2_wp_V_read );

    SC_METHOD(thread_grp_dog_func_1_fu_142_in_V);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_5 );
    sensitive << ( line_buffer_delay_outs_V_q0 );
    sensitive << ( reg_177 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_reg_ptbuf_in_V );

    SC_METHOD(thread_grp_dog_func_1_fu_142_tmp_5);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );

    SC_METHOD(thread_in_V_blk_n);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_5 );
    sensitive << ( in_V_ap_vld );

    SC_METHOD(thread_line_buffer_delay_outs_V_addr_1_reg_229);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_line_buffer_delay_outs_V_addr_reg_234);
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );

    SC_METHOD(thread_line_buffer_delay_outs_V_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( line_buffer_delay_outs_V_addr_1_reg_229 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );

    SC_METHOD(thread_line_buffer_delay_outs_V_address1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( line_buffer_delay_outs_V_addr_reg_234 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );

    SC_METHOD(thread_line_buffer_delay_outs_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );

    SC_METHOD(thread_line_buffer_delay_outs_V_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );

    SC_METHOD(thread_line_buffer_delay_outs_V_d0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( grp_dog_func_1_fu_142_ap_return_0 );

    SC_METHOD(thread_line_buffer_delay_outs_V_d1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( grp_dog_func_1_fu_142_ap_return_0 );

    SC_METHOD(thread_line_buffer_delay_outs_V_we0);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );

    SC_METHOD(thread_line_buffer_delay_outs_V_we1);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );

    SC_METHOD(thread_line_buffer_delays_buffer_V_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( grp_dog_func_1_fu_142_delay_buffer_V_address0 );

    SC_METHOD(thread_line_buffer_delays_buffer_V_address1);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( grp_dog_func_1_fu_142_delay_buffer_V_address1 );

    SC_METHOD(thread_line_buffer_delays_buffer_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_5 );
    sensitive << ( in_V_ap_vld );
    sensitive << ( ap_sig_cseq_ST_pp0_stg2_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg4_fsm_4 );
    sensitive << ( grp_dog_func_1_fu_142_delay_buffer_V_ce0 );

    SC_METHOD(thread_line_buffer_delays_buffer_V_ce1);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_5 );
    sensitive << ( in_V_ap_vld );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( grp_dog_func_1_fu_142_delay_buffer_V_ce1 );

    SC_METHOD(thread_line_buffer_delays_buffer_V_d1);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( grp_dog_func_1_fu_142_delay_buffer_V_d1 );

    SC_METHOD(thread_line_buffer_delays_buffer_V_we1);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg5_fsm_5 );
    sensitive << ( in_V_ap_vld );
    sensitive << ( ap_sig_cseq_ST_pp0_stg3_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( grp_dog_func_1_fu_142_delay_buffer_V_we1 );

    SC_METHOD(thread_out_data_V_write_assign_fu_183_p4);
    sensitive << ( reg_177 );
    sensitive << ( line_buffer_delay_outs_V_load_1_reg_240 );
    sensitive << ( line_buffer_delay_outs_V_load_2_reg_252 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( in_V_ap_vld );
    sensitive << ( ap_sig_pprstidle_pp0 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000001";
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_iter0_preg = SC_LOGIC_0;
    ap_reg_grp_dog_func_1_fu_142_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dog_func_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_V_ap_vld, "(port)in_V_ap_vld");
    sc_trace(mVcdFile, line_buffer_delays_0_wp_V_read, "(port)line_buffer_delays_0_wp_V_read");
    sc_trace(mVcdFile, line_buffer_delays_1_wp_V_read, "(port)line_buffer_delays_1_wp_V_read");
    sc_trace(mVcdFile, line_buffer_delays_2_wp_V_read, "(port)line_buffer_delays_2_wp_V_read");
    sc_trace(mVcdFile, line_buffer_delays_0_rp_V_read, "(port)line_buffer_delays_0_rp_V_read");
    sc_trace(mVcdFile, line_buffer_delays_1_rp_V_read, "(port)line_buffer_delays_1_rp_V_read");
    sc_trace(mVcdFile, line_buffer_delays_2_rp_V_read, "(port)line_buffer_delays_2_rp_V_read");
    sc_trace(mVcdFile, line_buffer_delays_buffer_V_address0, "(port)line_buffer_delays_buffer_V_address0");
    sc_trace(mVcdFile, line_buffer_delays_buffer_V_ce0, "(port)line_buffer_delays_buffer_V_ce0");
    sc_trace(mVcdFile, line_buffer_delays_buffer_V_q0, "(port)line_buffer_delays_buffer_V_q0");
    sc_trace(mVcdFile, line_buffer_delays_buffer_V_address1, "(port)line_buffer_delays_buffer_V_address1");
    sc_trace(mVcdFile, line_buffer_delays_buffer_V_ce1, "(port)line_buffer_delays_buffer_V_ce1");
    sc_trace(mVcdFile, line_buffer_delays_buffer_V_we1, "(port)line_buffer_delays_buffer_V_we1");
    sc_trace(mVcdFile, line_buffer_delays_buffer_V_d1, "(port)line_buffer_delays_buffer_V_d1");
    sc_trace(mVcdFile, line_buffer_delay_outs_V_address0, "(port)line_buffer_delay_outs_V_address0");
    sc_trace(mVcdFile, line_buffer_delay_outs_V_ce0, "(port)line_buffer_delay_outs_V_ce0");
    sc_trace(mVcdFile, line_buffer_delay_outs_V_we0, "(port)line_buffer_delay_outs_V_we0");
    sc_trace(mVcdFile, line_buffer_delay_outs_V_d0, "(port)line_buffer_delay_outs_V_d0");
    sc_trace(mVcdFile, line_buffer_delay_outs_V_q0, "(port)line_buffer_delay_outs_V_q0");
    sc_trace(mVcdFile, line_buffer_delay_outs_V_address1, "(port)line_buffer_delay_outs_V_address1");
    sc_trace(mVcdFile, line_buffer_delay_outs_V_ce1, "(port)line_buffer_delay_outs_V_ce1");
    sc_trace(mVcdFile, line_buffer_delay_outs_V_we1, "(port)line_buffer_delay_outs_V_we1");
    sc_trace(mVcdFile, line_buffer_delay_outs_V_d1, "(port)line_buffer_delay_outs_V_d1");
    sc_trace(mVcdFile, line_buffer_delay_outs_V_q1, "(port)line_buffer_delay_outs_V_q1");
    sc_trace(mVcdFile, in_V, "(port)in_V");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, in_V_blk_n, "(port)in_V_blk_n");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_0, "ap_sig_cseq_ST_pp0_stg0_fsm_0");
    sc_trace(mVcdFile, ap_sig_23, "ap_sig_23");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg5_fsm_5, "ap_sig_cseq_ST_pp0_stg5_fsm_5");
    sc_trace(mVcdFile, ap_sig_43, "ap_sig_43");
    sc_trace(mVcdFile, reg_177, "reg_177");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg2_fsm_2, "ap_sig_cseq_ST_pp0_stg2_fsm_2");
    sc_trace(mVcdFile, ap_sig_96, "ap_sig_96");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg3_fsm_3, "ap_sig_cseq_ST_pp0_stg3_fsm_3");
    sc_trace(mVcdFile, ap_sig_104, "ap_sig_104");
    sc_trace(mVcdFile, line_buffer_delay_outs_V_addr_1_reg_229, "line_buffer_delay_outs_V_addr_1_reg_229");
    sc_trace(mVcdFile, line_buffer_delay_outs_V_addr_reg_234, "line_buffer_delay_outs_V_addr_reg_234");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg1_fsm_1, "ap_sig_cseq_ST_pp0_stg1_fsm_1");
    sc_trace(mVcdFile, ap_sig_120, "ap_sig_120");
    sc_trace(mVcdFile, line_buffer_delay_outs_V_load_1_reg_240, "line_buffer_delay_outs_V_load_1_reg_240");
    sc_trace(mVcdFile, line_buffer_delay_outs_V_load_2_reg_252, "line_buffer_delay_outs_V_load_2_reg_252");
    sc_trace(mVcdFile, line_buffer_delays_2_wp_V_wri_reg_257, "line_buffer_delays_2_wp_V_wri_reg_257");
    sc_trace(mVcdFile, line_buffer_delays_2_rp_V_wri_reg_262, "line_buffer_delays_2_rp_V_wri_reg_262");
    sc_trace(mVcdFile, line_buffer_delays_1_wp_V_wri_reg_267, "line_buffer_delays_1_wp_V_wri_reg_267");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg4_fsm_4, "ap_sig_cseq_ST_pp0_stg4_fsm_4");
    sc_trace(mVcdFile, ap_sig_137, "ap_sig_137");
    sc_trace(mVcdFile, line_buffer_delays_1_rp_V_wri_reg_272, "line_buffer_delays_1_rp_V_wri_reg_272");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_iter0_preg, "ap_reg_ppiten_pp0_iter0_preg");
    sc_trace(mVcdFile, ap_reg_ptbuf_line_buffer_delays_0_wp_V_read, "ap_reg_ptbuf_line_buffer_delays_0_wp_V_read");
    sc_trace(mVcdFile, ap_reg_ptbuf_line_buffer_delays_1_wp_V_read, "ap_reg_ptbuf_line_buffer_delays_1_wp_V_read");
    sc_trace(mVcdFile, ap_reg_ptbuf_line_buffer_delays_2_wp_V_read, "ap_reg_ptbuf_line_buffer_delays_2_wp_V_read");
    sc_trace(mVcdFile, ap_reg_ptbuf_line_buffer_delays_0_rp_V_read, "ap_reg_ptbuf_line_buffer_delays_0_rp_V_read");
    sc_trace(mVcdFile, ap_reg_ptbuf_line_buffer_delays_1_rp_V_read, "ap_reg_ptbuf_line_buffer_delays_1_rp_V_read");
    sc_trace(mVcdFile, ap_reg_ptbuf_line_buffer_delays_2_rp_V_read, "ap_reg_ptbuf_line_buffer_delays_2_rp_V_read");
    sc_trace(mVcdFile, ap_reg_ptbuf_in_V, "ap_reg_ptbuf_in_V");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_ap_start, "grp_dog_func_1_fu_142_ap_start");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_ap_done, "grp_dog_func_1_fu_142_ap_done");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_ap_idle, "grp_dog_func_1_fu_142_ap_idle");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_ap_ready, "grp_dog_func_1_fu_142_ap_ready");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_ap_ce, "grp_dog_func_1_fu_142_ap_ce");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_delay_wp_V_read, "grp_dog_func_1_fu_142_delay_wp_V_read");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_delay_rp_V_read, "grp_dog_func_1_fu_142_delay_rp_V_read");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_delay_buffer_V_address0, "grp_dog_func_1_fu_142_delay_buffer_V_address0");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_delay_buffer_V_ce0, "grp_dog_func_1_fu_142_delay_buffer_V_ce0");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_delay_buffer_V_address1, "grp_dog_func_1_fu_142_delay_buffer_V_address1");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_delay_buffer_V_ce1, "grp_dog_func_1_fu_142_delay_buffer_V_ce1");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_delay_buffer_V_we1, "grp_dog_func_1_fu_142_delay_buffer_V_we1");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_delay_buffer_V_d1, "grp_dog_func_1_fu_142_delay_buffer_V_d1");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_tmp_5, "grp_dog_func_1_fu_142_tmp_5");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_in_V, "grp_dog_func_1_fu_142_in_V");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_ap_return_0, "grp_dog_func_1_fu_142_ap_return_0");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_ap_return_1, "grp_dog_func_1_fu_142_ap_return_1");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_ap_return_2, "grp_dog_func_1_fu_142_ap_return_2");
    sc_trace(mVcdFile, grp_dog_func_1_fu_142_in_V_blk_n, "grp_dog_func_1_fu_142_in_V_blk_n");
    sc_trace(mVcdFile, ap_reg_grp_dog_func_1_fu_142_ap_start, "ap_reg_grp_dog_func_1_fu_142_ap_start");
    sc_trace(mVcdFile, out_data_V_write_assign_fu_183_p4, "out_data_V_write_assign_fu_183_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_pprstidle_pp0, "ap_sig_pprstidle_pp0");
#endif

    }
}

dog_func::~dog_func() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_dog_func_1_fu_142;
}

void dog_func::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dog_func::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_pp0_stg0_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_dog_func_1_fu_142_ap_start = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
              !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))))) {
            ap_reg_grp_dog_func_1_fu_142_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_dog_func_1_fu_142_ap_ready.read())) {
            ap_reg_grp_dog_func_1_fu_142_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
             !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_5.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(in_V_ap_vld.read(), ap_const_logic_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_reg_ppiten_pp0_it0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_iter0_preg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
            ap_reg_ppiten_pp0_iter0_preg = ap_start.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())) {
            reg_177 = line_buffer_delay_outs_V_q0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) {
            reg_177 = line_buffer_delay_outs_V_q1.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_ptbuf_in_V = in_V.read();
        ap_reg_ptbuf_line_buffer_delays_0_rp_V_read = line_buffer_delays_0_rp_V_read.read();
        ap_reg_ptbuf_line_buffer_delays_0_wp_V_read = line_buffer_delays_0_wp_V_read.read();
        ap_reg_ptbuf_line_buffer_delays_1_rp_V_read = line_buffer_delays_1_rp_V_read.read();
        ap_reg_ptbuf_line_buffer_delays_1_wp_V_read = line_buffer_delays_1_wp_V_read.read();
        ap_reg_ptbuf_line_buffer_delays_2_rp_V_read = line_buffer_delays_2_rp_V_read.read();
        ap_reg_ptbuf_line_buffer_delays_2_wp_V_read = line_buffer_delays_2_wp_V_read.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()))) {
        line_buffer_delay_outs_V_load_1_reg_240 = line_buffer_delay_outs_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read()))) {
        line_buffer_delay_outs_V_load_2_reg_252 = line_buffer_delay_outs_V_q0.read();
        line_buffer_delays_2_rp_V_wri_reg_262 = grp_dog_func_1_fu_142_ap_return_2.read();
        line_buffer_delays_2_wp_V_wri_reg_257 = grp_dog_func_1_fu_142_ap_return_1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read()))) {
        line_buffer_delays_1_rp_V_wri_reg_272 = grp_dog_func_1_fu_142_ap_return_2.read();
        line_buffer_delays_1_wp_V_wri_reg_267 = grp_dog_func_1_fu_142_ap_return_1.read();
    }
}

void dog_func::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dog_func::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dog_func::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_5.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(in_V_ap_vld.read(), ap_const_logic_0)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dog_func::thread_ap_reg_ppiten_pp0_it0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
        ap_reg_ppiten_pp0_it0 = ap_start.read();
    } else {
        ap_reg_ppiten_pp0_it0 = ap_reg_ppiten_pp0_iter0_preg.read();
    }
}

void dog_func::thread_ap_return_0() {
    ap_return_0 = grp_dog_func_1_fu_142_ap_return_1.read();
}

void dog_func::thread_ap_return_1() {
    ap_return_1 = line_buffer_delays_1_wp_V_wri_reg_267.read();
}

void dog_func::thread_ap_return_2() {
    ap_return_2 = line_buffer_delays_2_wp_V_wri_reg_257.read();
}

void dog_func::thread_ap_return_3() {
    ap_return_3 = grp_dog_func_1_fu_142_ap_return_2.read();
}

void dog_func::thread_ap_return_4() {
    ap_return_4 = line_buffer_delays_1_rp_V_wri_reg_272.read();
}

void dog_func::thread_ap_return_5() {
    ap_return_5 = line_buffer_delays_2_rp_V_wri_reg_262.read();
}

void dog_func::thread_ap_return_6() {
    ap_return_6 = out_data_V_write_assign_fu_183_p4.read();
}

void dog_func::thread_ap_sig_104() {
    ap_sig_104 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void dog_func::thread_ap_sig_120() {
    ap_sig_120 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dog_func::thread_ap_sig_137() {
    ap_sig_137 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void dog_func::thread_ap_sig_23() {
    ap_sig_23 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dog_func::thread_ap_sig_43() {
    ap_sig_43 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void dog_func::thread_ap_sig_96() {
    ap_sig_96 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dog_func::thread_ap_sig_cseq_ST_pp0_stg0_fsm_0() {
    if (ap_sig_23.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = ap_const_logic_0;
    }
}

void dog_func::thread_ap_sig_cseq_ST_pp0_stg1_fsm_1() {
    if (ap_sig_120.read()) {
        ap_sig_cseq_ST_pp0_stg1_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg1_fsm_1 = ap_const_logic_0;
    }
}

void dog_func::thread_ap_sig_cseq_ST_pp0_stg2_fsm_2() {
    if (ap_sig_96.read()) {
        ap_sig_cseq_ST_pp0_stg2_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg2_fsm_2 = ap_const_logic_0;
    }
}

void dog_func::thread_ap_sig_cseq_ST_pp0_stg3_fsm_3() {
    if (ap_sig_104.read()) {
        ap_sig_cseq_ST_pp0_stg3_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg3_fsm_3 = ap_const_logic_0;
    }
}

void dog_func::thread_ap_sig_cseq_ST_pp0_stg4_fsm_4() {
    if (ap_sig_137.read()) {
        ap_sig_cseq_ST_pp0_stg4_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg4_fsm_4 = ap_const_logic_0;
    }
}

void dog_func::thread_ap_sig_cseq_ST_pp0_stg5_fsm_5() {
    if (ap_sig_43.read()) {
        ap_sig_cseq_ST_pp0_stg5_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg5_fsm_5 = ap_const_logic_0;
    }
}

void dog_func::thread_ap_sig_pprstidle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it0.read()))) {
        ap_sig_pprstidle_pp0 = ap_const_logic_1;
    } else {
        ap_sig_pprstidle_pp0 = ap_const_logic_0;
    }
}

void dog_func::thread_grp_dog_func_1_fu_142_ap_ce() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_5.read()) && 
          esl_seteq<1,1,1>(in_V_ap_vld.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        grp_dog_func_1_fu_142_ap_ce = ap_const_logic_0;
    } else {
        grp_dog_func_1_fu_142_ap_ce = ap_const_logic_1;
    }
}

void dog_func::thread_grp_dog_func_1_fu_142_ap_start() {
    grp_dog_func_1_fu_142_ap_start = ap_reg_grp_dog_func_1_fu_142_ap_start.read();
}

void dog_func::thread_grp_dog_func_1_fu_142_delay_rp_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_5.read())) {
            grp_dog_func_1_fu_142_delay_rp_V_read = ap_reg_ptbuf_line_buffer_delays_0_rp_V_read.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())) {
            grp_dog_func_1_fu_142_delay_rp_V_read = ap_reg_ptbuf_line_buffer_delays_1_rp_V_read.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_dog_func_1_fu_142_delay_rp_V_read = ap_reg_ptbuf_line_buffer_delays_2_rp_V_read.read();
        } else {
            grp_dog_func_1_fu_142_delay_rp_V_read = "XXXXXXXXXX";
        }
    } else {
        grp_dog_func_1_fu_142_delay_rp_V_read = "XXXXXXXXXX";
    }
}

void dog_func::thread_grp_dog_func_1_fu_142_delay_wp_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_5.read())) {
            grp_dog_func_1_fu_142_delay_wp_V_read = ap_reg_ptbuf_line_buffer_delays_0_wp_V_read.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())) {
            grp_dog_func_1_fu_142_delay_wp_V_read = ap_reg_ptbuf_line_buffer_delays_1_wp_V_read.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_dog_func_1_fu_142_delay_wp_V_read = ap_reg_ptbuf_line_buffer_delays_2_wp_V_read.read();
        } else {
            grp_dog_func_1_fu_142_delay_wp_V_read = "XXXXXXXXXX";
        }
    } else {
        grp_dog_func_1_fu_142_delay_wp_V_read = "XXXXXXXXXX";
    }
}

void dog_func::thread_grp_dog_func_1_fu_142_in_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_5.read())) {
            grp_dog_func_1_fu_142_in_V = ap_reg_ptbuf_in_V.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())) {
            grp_dog_func_1_fu_142_in_V = reg_177.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_dog_func_1_fu_142_in_V = line_buffer_delay_outs_V_q0.read();
        } else {
            grp_dog_func_1_fu_142_in_V =  (sc_lv<8>) ("XXXXXXXX");
        }
    } else {
        grp_dog_func_1_fu_142_in_V =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void dog_func::thread_grp_dog_func_1_fu_142_tmp_5() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_5.read())) {
            grp_dog_func_1_fu_142_tmp_5 = ap_const_lv3_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg3_fsm_3.read())) {
            grp_dog_func_1_fu_142_tmp_5 = ap_const_lv3_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_dog_func_1_fu_142_tmp_5 = ap_const_lv3_2;
        } else {
            grp_dog_func_1_fu_142_tmp_5 =  (sc_lv<3>) ("XXX");
        }
    } else {
        grp_dog_func_1_fu_142_tmp_5 =  (sc_lv<3>) ("XXX");
    }
}

void dog_func::thread_in_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg5_fsm_5.read()))) {
        in_V_blk_n = in_V_ap_vld.read();
    } else {
        in_V_blk_n = ap_const_logic_1;
    }
}

void dog_func::thread_line_buffer_delay_outs_V_addr_1_reg_229() {
    line_buffer_delay_outs_V_addr_1_reg_229 =  (sc_lv<2>) (ap_const_lv64_1);
}

void dog_func::thread_line_buffer_delay_outs_V_addr_reg_234() {
    line_buffer_delay_outs_V_addr_reg_234 =  (sc_lv<2>) (ap_const_lv64_0);
}

void dog_func::thread_line_buffer_delay_outs_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) {
            line_buffer_delay_outs_V_address0 = line_buffer_delay_outs_V_addr_1_reg_229.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) {
            line_buffer_delay_outs_V_address0 =  (sc_lv<2>) (ap_const_lv64_0);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            line_buffer_delay_outs_V_address0 =  (sc_lv<2>) (ap_const_lv64_2);
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            line_buffer_delay_outs_V_address0 =  (sc_lv<2>) (ap_const_lv64_1);
        } else {
            line_buffer_delay_outs_V_address0 =  (sc_lv<2>) ("XX");
        }
    } else {
        line_buffer_delay_outs_V_address0 =  (sc_lv<2>) ("XX");
    }
}

void dog_func::thread_line_buffer_delay_outs_V_address1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        line_buffer_delay_outs_V_address1 = line_buffer_delay_outs_V_addr_reg_234.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read()))) {
        line_buffer_delay_outs_V_address1 =  (sc_lv<2>) (ap_const_lv64_2);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()))) {
        line_buffer_delay_outs_V_address1 =  (sc_lv<2>) (ap_const_lv64_0);
    } else {
        line_buffer_delay_outs_V_address1 =  (sc_lv<2>) ("XX");
    }
}

void dog_func::thread_line_buffer_delay_outs_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))))) {
        line_buffer_delay_outs_V_ce0 = ap_const_logic_1;
    } else {
        line_buffer_delay_outs_V_ce0 = ap_const_logic_0;
    }
}

void dog_func::thread_line_buffer_delay_outs_V_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))))) {
        line_buffer_delay_outs_V_ce1 = ap_const_logic_1;
    } else {
        line_buffer_delay_outs_V_ce1 = ap_const_logic_0;
    }
}

void dog_func::thread_line_buffer_delay_outs_V_d0() {
    line_buffer_delay_outs_V_d0 = grp_dog_func_1_fu_142_ap_return_0.read();
}

void dog_func::thread_line_buffer_delay_outs_V_d1() {
    line_buffer_delay_outs_V_d1 = grp_dog_func_1_fu_142_ap_return_0.read();
}

void dog_func::thread_line_buffer_delay_outs_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg4_fsm_4.read())))) {
        line_buffer_delay_outs_V_we0 = ap_const_logic_1;
    } else {
        line_buffer_delay_outs_V_we0 = ap_const_logic_0;
    }
}

void dog_func::thread_line_buffer_delay_outs_V_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg2_fsm_2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))))) {
        line_buffer_delay_outs_V_we1 = ap_const_logic_1;
    } else {
        line_buffer_delay_outs_V_we1 = ap_const_logic_0;
    }
}

void dog_func::thread_line_buffer_delays_buffer_V_address0() {
    line_buffer_delays_buffer_V_address0 = grp_dog_func_1_fu_142_delay_buffer_V_address0.read();
}

void dog_func::thread_line_buffer_delays_buffer_V_address1() {
    line_buffer_delays_buffer_V_address1 = grp_dog_func_1_fu_142_delay_buffer_V_address1.read();
}

void dog_func::thread_line_buffer_delays_buffer_V_ce0() {
    line_buffer_delays_buffer_V_ce0 = grp_dog_func_1_fu_142_delay_buffer_V_ce0.read();
}

void dog_func::thread_line_buffer_delays_buffer_V_ce1() {
    line_buffer_delays_buffer_V_ce1 = grp_dog_func_1_fu_142_delay_buffer_V_ce1.read();
}

void dog_func::thread_line_buffer_delays_buffer_V_d1() {
    line_buffer_delays_buffer_V_d1 = grp_dog_func_1_fu_142_delay_buffer_V_d1.read();
}

void dog_func::thread_line_buffer_delays_buffer_V_we1() {
    line_buffer_delays_buffer_V_we1 = grp_dog_func_1_fu_142_delay_buffer_V_we1.read();
}

void dog_func::thread_out_data_V_write_assign_fu_183_p4() {
    out_data_V_write_assign_fu_183_p4 = esl_concat<16,8>(esl_concat<8,8>(line_buffer_delay_outs_V_load_2_reg_252.read(), line_buffer_delay_outs_V_load_1_reg_240.read()), reg_177.read());
}

void dog_func::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_pprstidle_pp0.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_1;
            } else if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_pprstidle_pp0.read()))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_pp0_stg2_fsm_2;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_pp0_stg3_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_pp0_stg4_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_pp0_stg5_fsm_5;
            break;
        case 32 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(in_V_ap_vld.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg5_fsm_5;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

}

